aimclub/FEDOT

- requirements.txt
Гитхаб ругается, что в pillow версии < 7.1.0 есть проблемы с безопасностью.
Поправил версию в requirements.txt
> Fix Pillow security issues

- benchmark/test_cases/scoring/scoring_case.py
- core/composer/node.py
- core/models/data.py
- core/models/evaluation/automl_eval.py
- core/models/evaluation/data_evaluation.py
- core/models/evaluation/evaluation.py
- core/models/evaluation/hyperparams.py
- core/models/evaluation/keras_eval.py
- core/models/evaluation/stats_models_eval.py
- core/models/model.py
- core/models/preprocessing.py
- core/repository/data/model_repository.json
- examples/chain_from_automl.py
- requirements.txt
- test/test_classification.py
- test/test_data.py
- test/test_forecasting.py
- test/test_model.py
- test/test_node.py
- test/test_preprocessing.py
- test/test_tuning.py
Накидал небольшие изменения по преобразованию features.
1. Сократил число дублирующегося кода в nodes. Кмк стало компактнее и удобнее, вроде ничего в процессе не сломалось. Порядок блоков остался прежний:
Transformer осуществляет преобразование форматов данных, preprocess - изменяет их "масштаб" через скейлинг/нормализацию и т.п.
2. Сделал возможность задавать тип препроцессинга в ноде "снаружи" - через поле manual_preprocessing_func.
Как минимум, пригодится для генерации бенчмарков, там с этим были проблемы.
3. Добавил реализацию модели-PCA, которая снижает размерность данных. Обильно не тестировал, но на примере в test_classifications.py внедрение PCA в цепочку даёт повышение качества.
Предлагаю пока использовать эту реализацию (добавив ещё несколько подобных моделей) для …
> Refactored preprocessing and PCA model

- core/composer/composer.py
- core/composer/optimisers/crossover.py
- core/composer/optimisers/inheritance.py
- core/composer/optimisers/mutation.py
- core/composer/optimisers/regularization.py
- core/composer/optimisers/selection.py
- core/models/evaluation/automl_eval.py
- core/repository/dataset_types.py
- core/repository/quality_metrics_repository.py
- core/repository/tasks.py
- core/utils.py
Был найден баг - при подключении федот-а как внешней либы возникает проблема со сравнением енумов, торчащих из пользовательского интерфейса наружу.
Сценарий такой. 
В своем стороннем проекте делается
from FEDOT.core.repository.tasks import TaskTypesEnum
и передаешь внутрь fedot переменную class_task =TaskTypesEnum.classification, то внутри fedot
где скрипт начинается с
from core.repository.tasks import TaskTypesEnum
и имеет сравнение енумов, то class_task не будет равно TaskTypesEnum.classification
(сравнение возвращает false, см. https://stackoverflow.com/questions/26589805/python-enums-across-modules).
Сделал в рамках этого PR фикс, но не знаю - можно ли его протестировать автоматически?
> Enum comparison bug fixed

- fedot/core/models/evaluation/evaluation.py
- fedot/core/models/model.py
- fedot/core/models/tuning/tuners.py
- test/chain/test_chain_tuning.py
Now, if the fine_tune method of the model in node returns None (e.g PCA, it means that the model can not be tuned), the whole chain tuning fails.
Example:
Traceback (most recent call last):
File "C:\Program Files\JetBrains\PyCharm 2019.3.1\plugins\python\helpers\pydev\pydevd.py", line 1434, in _exec
pydev_imports.execfile(file, globals, locals)  # execute the script
File "C:\Program Files\JetBrains\PyCharm 2019.3.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
exec(compile(contents+"\n", file, 'exec'), glob, loc)
File "D:\PycharmProjects\new fed\FEDOT\cases\credit_scoring_problem_multiobj.py", line 102, in <module>
run_credit_scoring_problem(full_path_train, full_path_test, is_visualise=True)
File "D:\PycharmProjects\new …
> Error with tuning the non-tunable models (e.g. PCA) fixed

- fedot/core/chains/chain_template.py
Появилась ошибка после переноса двух PR [first](https://github.com/nccr-itmo/FEDOT/pull/217) and [second]https://github.com/nccr-itmo/FEDOT/pull/210):
>           mkdir(name, mode)
E           OSError: [WinError 123] Синтаксическая ошибка в имени файла, имени папки или метке тома: 'D:\\THEODOR\\test\\January:12:2021, 13:41:40 PM test_chain_convert_to_json'
C:\Python37\lib\os.py:223: OSError
Исправлено на формат: 'January-12-2021,15-59-58,PM'.
> HOT FIX widows error

- examples/forecasting_model_composing.py
- examples/multiclass_prediction.py
- examples/time_series_forecasting.py
- fedot/core/algorithms/time_series/prediction.py
- fedot/core/chains/chain.py
- fedot/core/chains/ts_chain.py
- fedot/core/composer/gp_composer/gp_composer.py
- fedot/core/composer/metrics.py
- fedot/core/data/preprocessing.py
- fedot/core/data/transformation.py
- fedot/core/models/evaluation/evaluation.py
- fedot/core/repository/data/model_repository.json
- fedot/core/repository/tasks.py
- test/data_operations/test_transform.py
- test/real_applications/test_examples.py
- test/tasks/test_forecasting.py
Current problem: when placing some models for time series forecasting in PrimaryNode, an error occurs in the model's fit stage (for forecast_length > 1).
List of models that fails: xgbreg, adareg, gbr, svr, sgdr
List of models that work correctly: linear, lasso, ridge, knnreg, dtreg, treg, rfr
The bug fixed by with involvement  of MultiOutputRegressor that wraps the models that can not produce multivariate prediction directly (see https://stackoverflow.com/questions/39540123/muti-output-regression-in-xgboost).
Additional:
- multivariate target disable if it not necessary (to speed-up the fit of the ts models)
- ts compsing example extended
> Bug with regression models for the multivariate targets fixed

- .github/workflows/notify.yml
The telegram notifications about merges were added.
New Action is triggered by 'closed' status of pull requests. If the PR is merged the Action will send the PR information with link and description to chat. If the PR is closed manually the Action will send the information that this PR was just closed.
> Notify action

- requirements.txt
Pytest version in requirements was updated to the latest 6.2.3.
It allow one to reduce the dublicated logs during pytest run.
> Update pytest version in requirements

- fedot/core/repository/data/default_model_params.json
- test/unit/data_operations/test_data_operation_params.py
A bug that appeared when running on medical data has been fixed. 
Data feature: there are more features in dataset than objects. 
When initializing ransac_lin_reg, hyperparameter min_samples was defined by integer value. Now it is a real number (from 0.1 to 0.9, default value is 0.4).
> Correct RANSAC operation parameters

- fedot/api/api_utils.py
- requirements.txt
- test/unit/api/test_api_utils.py
Based on this issue: https://github.com/ITMO-NSS-team/fedot_electro_ts_case/issues/1
Previously, if `tuner_metric=None` in compose_fedot_model, a message in log is given: 'Default loss function was set'.
Now it is more user-friendly:
> Change logging when default tuner metric is set

- test/unit/test_logger.py
Now the test_logger_write_logs_correctly checks not for the last recorded message, but for the fact that there is a message in the logs
In the future, you may need to figure out why the logger sometimes returns messages in the wrong order
> Fix logger test

- examples/time_series/ts_custom_model_tuning.py
- fedot/api/help.py
- fedot/core/operations/evaluation/custom.py
- fedot/core/operations/evaluation/operation_implementations/models/custom_model.py
- test/unit/models/test_custom_model_introduction.py
- test/unit/models/test_model.py
In the previous implementation of custom strategy only predicting was available for user's models, now both fit and predict methods are available. It should be implemented as two functions with fixed structure and added to custom_params of custom_model node. Tests and examples for custom fit and predict model added.
> Custom model upgrading (issue #497)

- fedot/api/main.py
- fedot/core/data/data_preprocessing.py
- fedot/core/operations/evaluation/evaluation_interfaces.py
- fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
- test/unit/api/test_main_api.py
- test/unit/data_operations/test_data_operations_implementations.py
- test/unit/test_data_preprocessing.py
Modified the Imputer so that it can correctly handle integer features with unique values of 2 or less. 
For example, now `[1, 1, nan, 0]` will not be transformed into `[1, 1, 0.75, 0]`, but into `[1, 1, 1, 0]`. 
Another case: `[1, nan, nan, 0]` (the number of known categories is equal to each other). Then it will be converted inro `[1, 0.5, 0.5, 0]` 
Minor issues with preprocessing and processing of multi-output cases have also been corrected
> Improving binary feature processing

- fedot/core/data/merge.py
- fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_selectors.py
- fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
- fedot/preprocessing/data_types.py
- test/unit/data_operations/test_data_operations_implementations.py
- test/unit/pipelines/test_pipeline.py
- test/unit/tasks/test_forecasting.py
In this PR it was added the possibility to supply two time series to the input of the lagged operation. A bug has been fixed that occurred when poly_features was used in a time-series pipeline. 
A RFE processing was refactored also: It is now possible to reject features with less than 3 unique values.
> Improvement of time series processing

- examples/simple/interpretable/pipeline_explain.py
Example `examples/interpretable/pipeline_explain` used site function `get_simple_pipeline` that was renamed and moved during refactoring.
Fixed the issue by importing the function from its new location.
> Fix: Intepretability example was broken

- fedot/core/composer/cache.py
- fedot/core/composer/gp_composer/gp_composer.py
- fedot/core/pipelines/pipeline.py
- fedot/core/validation/compose/metric_estimation.py
- fedot/core/validation/compose/tabular.py
- fedot/core/validation/compose/time_series.py
- fedot/sensitivity/operations_hp_sensitivity/multi_operations_sensitivity.py
- fedot/sensitivity/operations_hp_sensitivity/one_operation_sensitivity.py
- test/unit/composer/test_composer.py
- test/unit/pipelines/test_node_cache.py
- test/unit/preprocessing/test_pipeline_preprocessing.py
- test/unit/preprocessing/test_preprocessors.py
- test/unit/validation/test_table_cv.py
Cache for fitted models is not working for CV-based metrics now.
This PR tries to fix it by the adding of fold-based supplementary ids for cache.
Main changes:
- preliminary data preparation for CV to improve performance and stability of results
- fit_from_scratch marked as obsolete, now the fit has the same behaviour
- fitted_on_data check removed as redunant
> Cross-validation support for cache

- .codecov.yml
'Sensetivity' folder excluded (since it is tested as integrational) as well as 'remote' (can not be tested directly)
> Test coverage corrected

- fedot/core/operations/operation_template.py
- fedot/core/pipelines/template.py
- test/unit/utilities/test_pipeline_import_export.py
In the folders with serialized models in the json files, the paths were written with "/" separator
Now the form of the record has been changed, now the paths are stored as a list, for example
```
"preprocessing": ["preprocessing","data_preprocessor.pkl"
```
The implementation is backward-compatible with the previous version
> OS-independent paths in serialization

- examples/advanced/fedot_based_solutions/external_optimizer.py
- fedot/api/api_utils/api_composer.py
- fedot/api/api_utils/initial_assumptions.py
- fedot/core/composer/gp_composer/specific_operators.py
- fedot/core/optimisers/gp_comp/operators/mutation.py
- fedot/core/pipelines/pipeline.py
- test/unit/api/test_api_utils.py
- test/unit/optimizer/test_gp_operators.py
Now the setting of composer_params['available_operations'] affects the initial assumption and mutations. The initial assumption is built only from the available operations and boosting mutation can no longer add nodes to the pipeline with operations/models that are not specified in the 'available_operations' (if composer_params['available_operations'] is specified)
> fix_available_operations

- fedot/core/pipelines/validation.py
- fedot/core/pipelines/validation_rules.py
- fedot/core/repository/data/data_operation_repository.json
- test/unit/pipelines/test_pipeline_comparison.py
- test/unit/pipelines/test_pipeline_validation.py
The rules for pipelines with the decompose operation have been modified. Now if two tasks will be solved simultaneously in a pipeline, such pipelines can be evaluated by the algorithm as correct and incorrect (based on the location of decompose operations or the absence of decompose operations)
> Modify validation rules for decompose

- fedot/api/api_utils/api_data.py
- fedot/api/main.py
- test/unit/api/test_api_utils.py
Earlier in this method, when calculating ROCAUC metric, predictions were redefined and probabilities were placed in `prediction.predict`. Then the probabilities were converted into labels
Now at the very beginning when calculating the metric for which labels are needed, predictions are given in labels
> fix get_metrics method

- test/unit/pipelines/test_pipeline.py
Fixed occasional test error when computational time of pipeline with higher time constraint was lower than computational time with less time constraint
Time constraint affects fit time, but fit time also fluctuates because of internal hardware reasons. The dispersion of this fluctuation seems to be constant. Therefore, if fit process is optimized, the fit time of both time constraint values in test is reduced, but dispersion remains the same. This raises the probability of dispersions' overlay and, hence, the test fail. Change of timeouts to 1 and 5 seconds provides stable work of test
> Fix test_pipeline_fit_time_constraint

- fedot/core/pipelines/tuning/tuner_interface.py
- test/unit/pipelines/test_pipeline_tuning.py
PipelineTuner is not able to optimize metrics that have formats that are different from to return of cv_tabular_predictions. Thus it is needed to operate cases when metrics required another format.
Examples: auc for binary classification, accuracy
> Added _calculate_loss_function with exception processing

- fedot/core/optimisers/gp_comp/operators/evaluation.py
Don't store un-pickle-able RemoteFitter in Evaluate, that prevented multiprocessing map
> hotfix multiprocessing in evaluate

- fedot/core/pipelines/validation.py
Due to redundant try-except block in validation block some exceptions don't float into main handler
It causes errors like "Metric evaluation error: ...." because invalid pipelines go throw evaluation
> Bug with unworking validation has solved

- fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
- requirements.txt
- test/unit/validation/test_time_series_cv.py
Because of lag in AutoReg prediction in fit_pipeline_stage **indices** (and numbers of rows without nan) **was different with target**.  In **AutoRegImplementation.predict** was added changing values to nan in _target_  the same way as in _predicted_.
> Bug 673 fixed

- fedot/core/log.py
- other_requirements/extra.txt
- requirements.txt
In existing implementation, if it is forbidden to edit /tmp/log.txt, then logger raises the exception after each usage.
The new code catches the PermissionError and disables in-file logger.
> Hotfix of PermissionError for logger

- examples/advanced/fedot_based_solutions/external_optimizer.py
- fedot/core/composer/gp_composer/gp_composer.py
- fedot/core/composer/random_composer.py
- fedot/core/optimisers/gp_comp/evaluation.py
- fedot/core/optimisers/gp_comp/gp_optimiser.py
- fedot/core/optimisers/gp_comp/operators/evaluation.py
- fedot/core/optimisers/gp_comp/operators/operator.py
- fedot/core/optimisers/gp_comp/operators/regularization.py
- fedot/core/optimisers/objective/__init__.py
- fedot/core/optimisers/objective/data_objective_eval.py
- fedot/core/optimisers/objective/objective.py
- fedot/core/optimisers/objective/objective_eval.py
- fedot/core/optimisers/optimizer.py
- test/unit/composer/test_history.py
- test/unit/optimizer/test_external.py
- test/unit/optimizer/test_gp_operators.py
- Use generic ObjectiveFunction (Callable) instead of ObjectiveEvaluate in .optimise interface.
This generalises Optimiser interface and allows passing arbitrary Callables as Objective functions.
- Introduce ObjectiveEvaluationDispatcher:
Dispatcher accepts objective function and returns population evaluator.
Its role is to define details of how objective must be actually evaluated,
e.g. using multiprocessing, evaluation cache or remote evaluation.
Rename EvaluationDispatcher to MultiprocessingDispatcher, which reflects its implementation.
- Introduce `evaluation_callback` functionality in Optimiser.
This allows extracting the need for computing intermediate metrics.
Now gp_composer defines this callback.
This is a continuation of PR #678 and part of the issue #608
> Generalize Evaluation subsystem and Objective interface

- cases/credit_scoring/credit_scoring_problem.py
- examples/advanced/fedot_based_solutions/external_optimizer.py
- fedot/core/dag/graph_operator.py
- fedot/core/optimisers/fitness/fitness.py
- fedot/core/optimisers/fitness/multi_objective_fitness.py
- fedot/core/optimisers/generation_keeper.py
- fedot/core/optimisers/gp_comp/gp_optimiser.py
- fedot/core/optimisers/gp_comp/individual.py
- fedot/core/optimisers/graph.py
- fedot/core/optimisers/opt_history.py
- fedot/core/optimisers/optimizer.py
- fedot/core/serializers/coders/opt_history_serialization.py
- test/unit/optimizer/test_generation_keeper.py
- test/unit/visualization/test_composing_history.py
In this PR, the H2O-like leaderboard is added. How to use:
`history.print_leaderboard()`
It consists of:
1) TOP 10 graphs obtained by optimiser
2) Initial assumptions
The main aim is to demonstrate for user how the optimised solution differs from initial one.
Example:
> Leaderboard added to OptHistory

- examples/advanced/time_series_forecasting/composing_pipelines.py
- examples/advanced/time_series_forecasting/multi_ts_arctic_forecasting.py
- examples/advanced/time_series_forecasting/multistep.py
- examples/simple/time_series_forecasting/ts_pipelines.py
- examples/simple/time_series_forecasting/tuning_pipelines.py
- fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
- fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/clstm.py
- fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/naive.py
- fedot/core/operations/evaluation/time_series.py
- fedot/core/pipelines/tuning/search_space.py
- fedot/core/repository/data/default_operation_params.json
- fedot/core/repository/data/model_repository.json
- test/unit/models/test_model.py
Two simple forecasting models were added as Implementations into FEDOT framework:
- LOCF - Last observation carried forward - repeats the last known value as many times as the number of elements in the forecast
- Naive average - the forecast is calculated as the average of the last n elements
> Naive forecasters for time series implemented 

- cases/credit_scoring/credit_scoring_problem_multiobj.py
- cases/multi_modal_genre_prediction.py
- examples/advanced/fedot_based_solutions/external_optimizer.py
- examples/advanced/fedot_based_solutions/graph_model_optimization.py
- examples/advanced/pipeline_sensitivity.py
- examples/advanced/sensitivity_analysis/pipelines_access.py
- examples/advanced/time_series_forecasting/composing_pipelines.py
- examples/advanced/time_series_forecasting/multi_ts_arctic_forecasting.py
- fedot/api/api_utils/api_composer.py
- fedot/api/api_utils/assumptions/assumptions_builder.py
- fedot/api/api_utils/presets.py
- fedot/api/main.py
- fedot/api/time.py
- fedot/core/composer/composer_builder.py
- fedot/core/composer/gp_composer/gp_composer.py
- fedot/core/composer/random_composer.py
- fedot/core/optimisers/gp_comp/gp_optimiser.py
- fedot/core/optimisers/opt_history.py
- fedot/core/optimisers/optimizer.py
- fedot/core/visualisation/opt_viz.py
- test/unit/api/test_main_api.py
- test/unit/api/test_presets.py
- test/unit/composer/test_builder.py
- test/unit/composer/test_composer.py
- test/unit/optimizer/test_external.py
- test/unit/tasks/test_custom.py
Many small changes in ApiComposer, mostly for readability and easier parameter passing:
- Simpler passing of initial assumptions
- Better separation between ApiComposer / Composre / ComposerBuilder (ApiComposer & Composer itself previously took some parts that better should be in ComposerBuilder)
- Some simplification of preset logic and code duplication removal
- Some simplification of tuner logic
Important changes in API:
- Optimisers now always return a sorted sequence of the best models (previously it could return 1 model for single-objective optimization, list for multi-objective). Instead, Composer can do that based on the best_models returned by Optimiser.
- API now doesn't have access to archive (HallOfFame) which I see as internal implementation detail. Instead, it has access …
> Refactor ApiComposer for simpler logic

- examples/simple/pipeline_and_history_visualization.py
- fedot/core/optimisers/opt_history.py
- fedot/core/repository/data/data_operation_repository.json
- fedot/core/repository/data/model_repository.json
- fedot/core/repository/operation_types_repository.py
- fedot/core/visualisation/opt_viz.py
- test/data/model_repository.json
- test/unit/models/test_repository.py
It is hard to track consistency of tags in repositories.
The new test will help developers to maintain this consistency.
Changelist:
* Added test asserting that all operations have informative tags from ones listed in `OperationTypesRepository`;
* Moved text preprocessing tools from models repository to data operations repository;
* Added new default tags;
* Default tags are now prioritized in reversed way;
* Minor fix of `OptHistory` visualization.
> Improve repositories tags consistency

- examples/advanced/automl/h2o_example.py
- examples/advanced/automl/tpot_example.py
- examples/advanced/remote_execution/remote_fit_example.py
- examples/advanced/sensitivity_analysis/pipeline_export_with_sa.py
- examples/simple/pipeline_import_export.py
- examples/simple/time_series_forecasting/clstm.py
- fedot/core/operations/atomized_template.py
- fedot/core/optimisers/gp_comp/evaluation.py
- fedot/core/pipelines/pipeline.py
- fedot/core/pipelines/template.py
- fedot/core/utilities/serializable.py
- fedot/remote/infrastructure/clients/client.py
- fedot/remote/infrastructure/clients/datamall_client.py
- fedot/remote/infrastructure/clients/test_client.py
- fedot/remote/remote_evaluator.py
- fedot/remote/run_pipeline.py
- fedot/utilities/project_import_export.py
- test/unit/models/test_atomized_model.py
- test/unit/models/test_custom_model_introduction.py
- test/unit/remote/test_remote_custom.py
- test/unit/utilities/test_pipeline_import_export.py
Minor PR with the following changes:
- Change RemoteEvaluator interface to accept any Serializable Graph instead of Pipeline
- Drop `pipeline.template` field because it's unused and creates unnecessary cycle between pipeline & its template
- Introduce `Serializable` interface with `save()` & `load()` methods. Pipeline now it is subclass.
- Replace loading of serialized pipeline with direct classmethod call `Pipeline.from_serialized`
Fixes #679
> Abstract RemoteEvaluator for any Serializable Graph

- examples/advanced/fedot_based_solutions/graph_model_optimization.py
- fedot/core/composer/random_composer.py
- fedot/core/dag/graph.py
- fedot/core/dag/graph_operator.py
- fedot/core/optimisers/gp_comp/gp_operators.py
- fedot/core/optimisers/gp_comp/operators/crossover.py
- fedot/core/optimisers/gp_comp/operators/mutation.py
- fedot/core/optimisers/graph.py
- fedot/core/pipelines/pipeline.py
- fedot/core/pipelines/tuning/sequential.py
- fedot/core/pipelines/verification_rules.py
- fedot/core/serializers/coders/graph_serialization.py
- fedot/sensitivity/deletion_methods/multi_times_analysis.py
- test/unit/dag/test_graph.py
- test/unit/dag/test_graph_operator.py
- test/unit/optimizer/test_gp_operators.py
- test/unit/pipelines/test_pipeline.py
- test/unit/serialization/mocks/serialization_mocks.py
- test/unit/serialization/test_encoder.py
- test/unit/tasks/test_custom.py
- test/unit/utilities/test_pipeline_import_export.py
- test/unit/visualization/test_visualisation_utils.py
Refactor Graph (& OptGraph) usages:
- Now `graph.operator` can not be used outside of graph
- Remove direct usaged of `graph.nodes`: now there is a private field `_nodes` and property `nodes`. However users can still modify nodes using this property
- Some methods (`sort_nodes` and `actualise_old_node_children`) were not moved to graph interface since they are not in use anywhere
> 743 refactor usages of graph

- examples/simple/pipeline_and_history_visualization.py
- fedot/core/optimisers/gp_comp/evaluation.py
- fedot/core/optimisers/graph.py
- fedot/core/optimisers/opt_history.py
- fedot/core/visualisation/graph_viz.py
- fedot/core/visualisation/opt_viz.py
- test/unit/composer/test_history.py
- test/unit/visualization/test_composing_history.py
* Colors of models in visualizations are picked by repository tags.
* Tags-based visualizations provide list of operations per tag.
* New visualizations: `fitness_line` and `fitness_line_interactive`.
The last one can be saved, then it shows the last pipeline without buttons.
- New histories gather time of evaluation for each individual. By default, such histories are visualized per time axis.
> `OptHistory` visualizations improvement

- fedot/core/operations/evaluation/operation_implementations/data_operations/text_pretrained.py
- fedot/core/visualisation/opt_viz.py
* Wrapped `gensim` import in `warn_requirement`.
* Fixed warning hint for `Pillow`.
> Hotfix wrap extra dependencies import

- fedot/core/optimisers/gp_comp/operators/crossover.py
- fedot/preprocessing/preprocessing.py
- fedot/preprocessing/structure.py
- test/unit/optimizer/test_gp_operators.py
Main change is that PipelineStructureAnalysis isn't stored in DataPreprocessor. This simplifes pickling/unpickling Pipeline with preprocessor because now it doesn't store nx.DiGraph with Nodes deep internally in preprocessor.structure_analysis.
It's required for #750, because in that PR there're problems with pickle due to changes in Graph implementation that tried to unpickle old variants of Nodes stored accidentally deep inside preprocessor.
> Simplify pickle-serialization of DataPreprocessor

- examples/advanced/pipeline_sensitivity.py
- fedot/core/dag/graph.py
- fedot/core/optimisers/graph.py
- fedot/core/optimisers/opt_history.py
- fedot/core/visualisation/graph_viz.py
- fedot/core/visualisation/opt_viz.py
- fedot/sensitivity/deletion_methods/multi_times_analysis.py
- fedot/utilities/project_import_export.py
- requirements.txt
- test/unit/visualization/test_composing_history.py
- test/unit/visualization/test_graph_visualizations.py
- test/unit/visualization/test_visualisation_utils.py
- Refactored default graph representations by matplotlib + networkx.
- Added 'pyvis' visualization engine for interactive graph views via html.
- Added 'graphviz' visualization engine (requires [Graphviz](https://graphviz.org/) and [pygraphviz](https://pygraphviz.github.io/)).
- Matplotlib visualization supports nodes_size and edges_curvature arguments.
- All graph and history visualizations now support `dpi` argument.
> `Graph` visualizations improvement

- examples/simple/pipeline_and_history_visualization.py
- examples/simple/pipeline_visualization.py
- fedot/core/dag/graph.py
- fedot/core/optimisers/graph.py
- fedot/core/optimisers/opt_history.py
- fedot/core/visualisation/graph_viz.py
- fedot/core/visualisation/opt_viz.py
- test/unit/visualization/test_composing_history.py
There was a critical bug that did not allow showing graphs with a single node.
Besides, a few features were added:
- Improved graphs visual scalability and choice of edge curvature direction;
- Parametrized node size and font size;
- `OptGraph` now uses labels-based color map without use of repository tags;
- All `OptHistory` tags-based animations now can be shown without use of tags, thus they can now visualize non-ML evolution histories.
> Fix & improve visualizations

- cases/credit_scoring/credit_scoring_problem_multiobj.py
- examples/simple/pipeline_and_history_visualization.py
- fedot/api/main.py
- fedot/core/optimisers/opt_history.py
- fedot/core/visualisation/graph_viz.py
- fedot/core/visualisation/opt_history/arg_constraint_wrapper.py
- fedot/core/visualisation/opt_history/fitness_box.py
- fedot/core/visualisation/opt_history/fitness_line.py
- fedot/core/visualisation/opt_history/history_visualization.py
- fedot/core/visualisation/opt_history/operations_animated_bar.py
- fedot/core/visualisation/opt_history/operations_kde.py
- fedot/core/visualisation/opt_history/utils.py
- fedot/core/visualisation/opt_viz.py
- fedot/core/visualisation/opt_viz_extra.py
- test/unit/visualization/test_visualisation_utils.py
History visualizations are now moved to the separate classes. Now they are much more convenient to use, as `history.show.*visualization_name*()` allows context search for all available visualizations, and the selected one is available directly with its signature and doc string. The older variant `history.show()` is still supported.
I also implemented a flexible constraints-tracking system. It is defined as a metaclass of visualizations that wraps all `.visualize()` calls with constraints checkers. There's currently two kinds of constraints available: parameter-specific and visualization-specific. 
The checkers have the following possibilities:
- throw exceptions, 
- send warnings via the visualization's logger,
- check the OptHistory content;
- modify kwargs.
> Refactor visualizations

- fedot/core/optimisers/gp_comp/evaluation.py
Due to some problems with memory and performance https://github.com/nccr-itmo/FEDOT/issues/840. Multiprocessing was refactored using joblib library
> Embedding joblib

- fedot/api/api_utils/assumptions/assumptions_builder.py
- fedot/core/repository/operation_types_repository.py
Fixes #767. The test there possibly fails because in it only 3 operations are allowed through cli. So there's not enoughg variability in pipeline generation because of just few operations, and sometimes all pipelines fail at evaluation stage, giving the AttributeError mentioned in the issue.
> Fix too restrictive operation filtering in assumptions_builder.py

- requirements.txt
As it is said [here](https://github.com/networkx/networkx/pull/5515#issue-1199131215) the [commit](https://github.com/networkx/networkx/commit/11db137b93f8f0b605cb8cefbeab21720348b9f7) related to networkx 2.7 breaks the order of layers in `multipartite_layout`, currently used for graphs visualization.
The [PR](https://github.com/networkx/networkx/pull/5705) fixes the issue. It relates to networkx 2.8.4, thus the versions 2.7, 2.8.1, 2.8.2 and 2.8.3 should not be used by FEDOT.
> Restrict bugged networkx versions

- examples/simple/classification/resample_example.py
- fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_imbalanced_class.py
- fedot/core/pipelines/tuning/search_space.py
- fedot/core/repository/data/default_operation_params.json
- test/unit/data_operations/test_data_operations_implementations.py
Solving another problem with resample operation from Issue https://github.com/nccr-itmo/FEDOT/issues/790. 
Bug was in replace parameter. In case of expanding strategy it causes difficulties and needed to change replace param to True. It is required to avoid error in sklearn method, which cannot create data if replace is False. Solution is to check this parameter and dynamically change it in process when it is required.
> 790 fix - Resample replace fix and operation refactoring

- fedot/api/api_utils/params.py
- test/unit/composer/test_history.py
- test/unit/optimizer/test_data_objective_eval.py
- test/unit/validation/test_table_cv.py
- test/unit/validation/test_time_series_cv.py
Changed default cv_folds number in params for table data and in some tests
> Default number of cv_folds is changed to 5

- test/unit/composer/test_history.py
Some of the recent changes broke `OptHistory` backward compatibility in a such way that individuals have been loaded with empty graphs. This was noticed by @staeros while utilizing [NAS](https://github.com/ITMO-NSS-team/nas-fedot). This bug was reproduced by me with the older "test_history.json". But tests didn't catch this error.
Since at this point we [refused](https://github.com/nccr-itmo/FEDOT/pull/863) to maintain backward compatibility anyway, this PR does not fix the bug. Instead, it provides a test for this situation not to be repeated in the future.
Plus, added a test for the properties of `Individual`.
> Add test for graphs in history

- test/unit/preprocessing/test_pipeline_preprocessing.py
- test/unit/preprocessing/test_preprocessors.py
Minor fix due to the fact that ohe in python 3.7 can not transform arrays with np.nan, it is possible since python version >= 3.8. 
**Explanation:**
In the failed test (_test_data_with_mixed_types_per_column_processed_correctly_), the data was split so that the type of the training part was defined as numerical with some str values + unique values count was < 13, so the final type of this column is a string. So firstly column was transformes to numerical (to avoid treating '1.0' and '1' numbers as different in general case) and then to categorical. Since there was only one truly string value in the test part, when preparing for the predict and going through a similar transformation path as for fit, when converting to a numeric value, we got np.nan, which could not be further encoded.
> Fix preprocessing tests on python 3.7

- fedot/core/visualisation/opt_history/operations_animated_bar.py
Pass an `ax` to `colorbar` according to [these changes](https://github.com/matplotlib/matplotlib/commit/5509ebbed92ba0dd90c03fa34713b5754c7007d0#diff-01b0c7a8c4445ae46a3c055ace167e99f59dcd54dbf04c84bca2132914d2f8dfR1247-R1263).
> Hotfix matplotlib

- fedot/core/serializers/coders/opt_history_serialization.py
- fedot/core/serializers/serializer.py
- test/integration/multiprocessing/test_history.py
- test/unit/composer/test_history.py
Hotfix for #896. Partly returns `OptHistory` consistency. 
**The main problem with history:** Sometimes initial assumptions (gen 0) are evaluated after increasing the population (gen 1) by mutations. In this case, individuals in gen 1 get parents without `native_generation` and `fitness`, because their parents are just copies of individuals from gen 0. Before these changes, not evaluated copies from "parents" were replacing the originals, and the final JSON got a bunch of individuals with empty `fitness` and `native_generation`. This bug was catched while evaluating cases in FEDOT.Web.
**Changes:** This PR makes `OptHistory` primarily choose individuals from generations when serializing.
> Hotfix OptHistory serialization

- examples/simple/time_series_forecasting/ts_pipelines.py
- fedot/core/optimisers/gp_comp/operators/operator.py
- fedot/core/optimisers/gp_comp/operators/selection.py
- test/unit/optimizer/test_selection_operators.py
- Made all selection types significantly faster.
- Made all selection types maintain default behavior: remove duplicate individuals and return a multiple instances of a single individual if only one individual was passed as a population.
- Made inheritance use one of competitive selection algorithms at a time, instead of their mixture.
> Selection minor refactoring

- fedot/core/optimisers/gp_comp/evaluation.py
- fedot/core/optimisers/opt_history_objects/individual.py
- fedot/core/optimisers/opt_history_objects/opt_history.py
- test/unit/composer/test_history.py
An attempt to minimize data exchange between processes by changing evaluation interface.
> Fix multiprocessing data exchange

- fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
Fast fix of sklearn warning `Deprecated since version 1.1: Starting in v1.3, whiten='unit-variance' will be used by default. whiten=True is deprecated from 1.1 and will raise ValueError in 1.3. Use whiten=arbitrary-variance instead.`
> Fix annoying sklearn warning

- fedot/core/dag/graph.py
- fedot/core/visualisation/graph_viz.py
- fedot/core/visualisation/opt_history/fitness_box.py
- fedot/core/visualisation/opt_history/fitness_line.py
- fedot/core/visualisation/opt_history/operations_animated_bar.py
- fedot/core/visualisation/opt_history/operations_kde.py
- fedot/core/visualisation/opt_history/utils.py
- Made default DPI equal to 100 for all matplotlib visualizations.
- Made width of the KDE legend more adaptive.
- Made plot size fixed where it is possible.
- Limited number of ticks for axes where it was necessary.
- Made `fitness_line` plotted per generations by default.
> Visualizations hotfixes

- fedot/core/optimisers/gp_comp/operators/selection.py
Let's say `len(individuals)` is the size of the original generation, `pop_size` is the size of the subsample.
The error occurred when the conditions matched:
- `len(individuals) >= 21`;
- `len(individuals) = pop_size + 1`.
> Hoftix tournament selection

- fedot/core/adapter/__init__.py
- fedot/core/adapter/adapter.py
- fedot/core/dag/graph.py
- fedot/core/dag/graph_delegate.py
- fedot/core/dag/graph_node.py
- fedot/core/dag/graph_utils.py
- fedot/core/dag/graph_verifier.py
- fedot/core/dag/linked_graph.py
- fedot/core/optimisers/adapters.py
- fedot/core/optimisers/graph.py
- fedot/core/optimisers/optimizer.py
- fedot/core/serializers/serializer.py
- test/unit/adapter/test_adapt_pipeline.py
Previously PipelineAdapter used a quite *hacky* way: it just was rewriting `__class__` field.
It's not the best approach, because it *assumes* that Pipeline & OptGraph have the same structure. This can lead to subtle bugs in the future if Pipeline and/or OptGraph implementations change.
This PR resolves this:
- It introduces a proper graph transformation function `map, that transforms each node directly and rebuilds all links in a DFS traverse.
- It implements new default `IdentityAdapter` instead of bug-prone `DirectAdapter` that was unconditionally rewriting `__class__` field
Overall, this properly isolates OptGraph-level from Pipeline-level, that's required for GOLEM
> Refactor PipelineAdapter (don't overwrite `__class__`)

- fedot/api/api_utils/api_composer.py
- fedot/core/composer/composer.py
- fedot/core/composer/composer_builder.py
- fedot/core/composer/gp_composer/gp_composer.py
- fedot/core/optimisers/composer_requirements.py
- fedot/core/optimisers/opt_history_objects/opt_history.py
- fedot/core/optimisers/optimizer.py
- fedot/core/optimisers/populational_optimizer.py
- fedot/core/visualisation/opt_viz_extra.py
- test/unit/composer/test_composer.py
- test/unit/composer/test_history.py
- test/unit/visualization/test_composing_history.py
Previous decision with hiding writing to opt history inside an opaque callback proved to be inconvenient.
Returning direct access to OptHistory from Optimizer
> OptHistory returns to GraphOptimizer

- fedot/core/serializers/coders/any_serialization.py
- test/unit/serialization/test_decoder.py
Small fix to make `any_from_json` more simple and stable, by avoiding calling `__init__`, instead creating object with `__new__`.
> Avoid calling object initialization while deserializing

- fedot/core/optimisers/gp_comp/gp_operators.py
- test/unit/optimizer/gp_operators/test_gp_operators.py
Depth of a graph after subtree replacement was calculated incorrectly and graphs with depth > max_depth were generated
> Fix replace_subtrees used for crossover

- cases/river_levels_prediction/river_level_case_manual.py
- examples/simple/pipeline_tune.py
- fedot/api/api_utils/api_composer.py
- fedot/api/main.py
- fedot/core/optimisers/objective/data_objective_eval.py
- fedot/core/optimisers/populational_optimizer.py
- fedot/core/pipelines/node.py
- fedot/core/pipelines/pipeline.py
- fedot/core/pipelines/tuning/search_space.py
- fedot/core/pipelines/tuning/tuner_interface.py
- fedot/core/pipelines/tuning/unified.py
- test/unit/pipelines/tuning/test_pipeline_tuning.py
Now PipelineTuner considers initial parameters of a pipeline.  To achive that, at first search is conducted using search space with fixed initial parameters. After that search is continued on the whole initial search space.
> Search near init params and some mini fixes

- cases/multi_ts_level_forecasting.py
- examples/simple/interpretable/api_explain.py
- examples/simple/time_series_forecasting/api_forecasting.py
- fedot/api/api_utils/assumptions/assumptions_builder.py
- fedot/api/api_utils/params.py
- fedot/api/api_utils/presets.py
- fedot/api/main.py
- fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
- fedot/core/optimisers/populational_optimizer.py
- fedot/core/repository/data/model_repository.json
- fedot/core/repository/operation_types_repository.py
Previously data_type was not used while getting suitable operations during model composition. That was causing problems described [here](https://github.com/aimclub/FEDOT/issues/974)
Changes:
- available_operations are defined during fit strage to take ```input_data.data_type``` into account
- new method ```ApiParams.update_available_operations_by_preset``` were created
- filterring operations by data_type in ```OperationTypesRepository.suitable_operations``` was fixed to not filter out to many operations
> Fix getting suitable operations for multi ts 

- fedot/core/pipelines/tuning/tuner_interface.py
- fedot/core/pipelines/tuning/unified.py
- test/unit/composer/test_composer.py
- test/unit/composer/test_history.py
- test/unit/optimizer/test_evaluation.py
- test/unit/pipelines/tuning/test_pipeline_tuning.py
- test/unit/validation/test_table_cv.py
The problem was with the way initial parameters were fixed in search space. When in search space a parameter had hp.loguniform distribution the evaluation was failing if the parameter was fixed using hp.choice((1, fixed_value)). 
Now search space is not modified, we just do not change initial parameters for some first iterations of tuning.
Some test were taking too much time so they were fixed to execute faster.
> Hotfix tuning with init params and some tests duration

- cases/multi_ts_level_forecasting.py
- examples/simple/time_series_forecasting/api_forecasting.py
- fedot/api/api_utils/api_data.py
- fedot/api/fedot_cli.py
- fedot/api/main.py
- fedot/core/data/data_split.py
- fedot/core/data/supplementary_data.py
- fedot/core/data/visualisation.py
- fedot/core/pipelines/ts_wrappers.py
- fedot/core/validation/split.py
- test/unit/api/test_main_api.py
- test/unit/tasks/test_forecasting.py
- test/unit/tasks/test_multi_ts_forecast.py
FEDOT API predict now can be in-sample. 
Output of  ``.predict(test_data)`` is a forecast with depth ``forecasting_length*validation_blocks``  using ``test_data.features[-forecasting_length*validation_blocks:]``.
Output of  ``.forecast(test_data)`` is a forecast with depth ``forecasting_length``, using ``test_data.features`` as pre_history. 
To get in-sample predict with n steps:
- use ``train_test_data_setup(train_input, validation_blocks=n)``
- ``model = Fedot(..., validation_blocks=n, ...)``
-  ``model.predict(test_data)``
- ``model.get_metrics()``
- ``model.plot_prediction()``
To get out-of-sample forecast with n steps:
- use ``train_test_data_setup(train_input)``
-  ``model.forecast(test_data, horison=forecast_length * n)``
- ``model.plot_prediction()``
Green line after vertical line …
> Predict for time series

- cases/multivariate_ts_forecasting.py
- fedot/api/api_utils/api_composer.py
- fedot/core/adapter/adapter.py
- fedot/core/optimisers/archive/generation_keeper.py
- fedot/core/optimisers/archive/individuals_containers.py
- fedot/core/optimisers/objective/metrics_objective.py
- fedot/core/optimisers/objective/objective.py
- test/integration/quality/test_quality_improvement.py
- test/unit/optimizer/fitness/test_fitness.py
These fixes came from experiments with abstract graph optimization (synthtic task) that seems necessary for the release.
Apparently, Multi-Objective optimization was broken. 
Also closes #997
> Release fixes for multi-objective optimization

- fedot/core/pipelines/tuning/tuner_interface.py
Sign of metric deviation is now correct. Deviation is changed from 5% to 0.05% - so if ```obtained_metric <= 100.05% * initial_metric``` we return tuned pipeline.
> Fix metric deviation

- fedot/core/composer/metrics.py
- fedot/core/optimisers/gp_comp/parameters/population_size.py
fixes minor issues #1011 and #1008
> recover from population size 1

- requirements.txt
According to this PR, Seaborn is not compatible with NumPy 1.24.0 due to a bug in the latter:
https://github.com/mwaskom/seaborn/pull/3194
Furthermore, the bug is going to be fixed by numpy 1.24.1:
https://github.com/numpy/numpy/milestone/114
Thus, restricting the bugged NumPy version only.
> Mark numpy 1.24.0 as non-compatible

- test/unit/composer/test_history.py
`np.shape` was misused in `test_history_backward_compatibility`.
> Fix history test

- fedot/core/data/data_split.py
- fedot/core/optimisers/objective/data_source_splitter.py
- test/unit/data/test_data_split.py
Fixed train test splin using Hold-out validation: now no new targes can appear in test subset.
> Train-test shape mismatch 

- test/unit/api/test_main_api.py
Hotfix unstable ts_forecasting test in PR #1021 after merging into master. Changed predefined preset from `auto` to `glm` in test to simplify it and to guarantee finding pipelines the optimal params.
> Hotfix #1021 after merging into master

- README.rst
- README_en.rst
The link to non-supported imdb example in readme changed to wine example
> Readme (ru&en) link hotfix

- examples/simple/time_series_forecasting/api_forecasting.py
- fedot/api/api_utils/api_composer.py
- fedot/api/api_utils/params.py
- fedot/api/main.py
plot_pareto was using ApiParams.metric_to_compose attribute which was not set anywere. Now metric names are obtained from api_composer.
This solution might be refactored after closing #1038
> Fix plot_pareto

- fedot/api/api_utils/api_composer.py
- test/unit/api/test_api_params.py
- test/unit/api/test_api_utils.py
- test/unit/composer/test_history.py
`Fedot(..., initial_assumption=...)` is expected to get a sequence of pipelines and pass them as initial graphs to an optimizer via composer.
Moreover, FEDOT itself generates more than one initial assumption by default.
As the result of this bug, composer passed only one of the initial assumptions to an optimizer.
This PR fixes the bug and adds the corresponding test.
> Fix initial assumptions as list of pipelines

- examples/advanced/multimodal_text_num_example.py
- fedot/api/api_utils/assumptions/task_assumptions.py
- fedot/core/pipelines/tuning/search_space.py
Added CatBoost to FEDOT initial assumptions for classification.
For the sake of stability, restricted tuning of the model's loss function.
> Add catboost to default initial assumptions

- fedot/utilities/memory.py
Memory consumption was printed by default, not logged.
> Minor logging fix

- fedot/api/api_utils/data_definition.py
- fedot/core/data/data.py
- fedot/preprocessing/preprocessing.py
- test/unit/data_operations/test_data_definition.py
- test/unit/data_operations/test_text_preprocessing.py
Solves [issue](https://github.com/aimclub/FEDOT/issues/1059)
Comparison of different approaches:
> 1059 timestamp bug

- fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
One line in code in lagged implementation spends more than 95% of lagged implementation evaluation time (in my case).
Fixed it.
> Lagged implementation speedup 

- fedot/api/api_utils/presets.py
- fedot/core/data/multi_modal.py
- fedot/core/operations/evaluation/custom.py
- fedot/core/operations/evaluation/evaluation_interfaces.py
- fedot/core/operations/evaluation/gpu/clustering.py
- fedot/core/operations/evaluation/gpu/common.py
- fedot/core/operations/evaluation/operation_implementations/data_operations/categorical_encoders.py
- fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/cgru.py
- fedot/core/operations/evaluation/text.py
- fedot/core/operations/evaluation/time_series.py
- fedot/core/operations/operation.py
- fedot/core/pipelines/pipeline_node_factory.py
- fedot/core/pipelines/tuning/hyperparams.py
- fedot/core/pipelines/verification_rules.py
- fedot/core/repository/pipeline_operation_repository.py
- fedot/utilities/random.py
- test/integration/real_applications/test_model_result_reproducing.py
FEDOT with set seed return the same pipeline for different compose processes for now.
> Fix random FEDOT results with set seed

- examples/advanced/time_series_forecasting/exogenous.py
- fedot/api/main.py
- fedot/core/pipelines/pipeline.py
Example for exogenous time series was addited to use API.
> Replace exogenous example

- docs/source/advanced/hyperparameters_tuning.rst
- fedot/core/pipelines/tuning/tuner_builder.py
- test/integration/pipelines/tuning/test_pipeline_tuning.py
- `TunerBuilder` fixed to initialize multi objective tuner
- Tests for multi objective tuning are added
- Documentation for tuning is updated
> Fix multiobj tuning

- examples/simple/classification/api_classification.py
- fedot/api/main.py
- test/integration/api/test_main_api.py
- test/unit/validation/test_table_cv.py
> Decimal places control implemented

- examples/advanced/time_series_forecasting/exogenous.py
- test/integration/cache/test_cache_parallel.py
- test/integration/real_applications/test_examples.py
- test/integration/real_applications/test_model_result_reproducing.py
- test/integration/remote/test_remote_composer.py
Made all integration tests pass.
> Integration tests fix

- .github/workflows/unit-build.yml
- fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
- fedot/core/pipelines/prediction_intervals/params.py
- fedot/core/pipelines/prediction_intervals/solvers/mutation_of_best_pipeline.py
- fedot/core/pipelines/prediction_intervals/ts_mutation.py
- fedot/core/pipelines/prediction_intervals/utils.py
- fedot/core/repository/data/data_operation_repository.json
- fedot/core/repository/data/default_operation_params.json
- fedot/core/repository/data/model_repository.json
- fedot/utilities/ts_gapfilling.py
- test/integration/models/test_model.py
- test/unit/api/test_api_params.py
- test/unit/data_operations/test_data_operation_params.py
- test/unit/pipelines/prediction_intervals/test_prediction_intervals.py
- test/unit/pipelines/test_pipeline_parameters.py
- test/unit/tasks/test_forecasting.py
- test/unit/validation/test_time_series_cv.py
Test does not pass until https://github.com/aimclub/GOLEM/pull/202 is not in release.
1. Fix #1173 + new test
2. Fix #1170 + new test (+ https://github.com/aimclub/GOLEM/pull/202)
3. Fix #1159
4. Add test for #262 
5. Add `verbose=0` for boosting models
6. Raise error if `window_size` is incorrect in `LaggedImplementation`.
7. Set `non-default` tag for CGRU and `ransac_non_lin_reg` due to high evaluation time.
8. Set `non-default` tag for `CutImplementation` due to specific type of operation.
9. Fix second point from #1165
10. Set `non-default` tag for `ExtraTreesRegressor` and `gbr` due to more effective alternatives.
> Fix some bugs

- fedot/core/data/data.py
- test/unit/data/test_data.py
Add InputData.from_dataframe and InputData.from_numpy methods. From dataframe expects that user already opend his df, set indeces, removed columns. From numpy based on exicting function.
> add InputData from pd and numpy

- docs/source/advanced/atomized_model.rst
Микрофикс примера в докуменации
>  Docs fix for atomized model

- fedot/core/operations/evaluation/operation_implementations/models/keras.py
Я заметил, что если обучить CNN модель для классификации изображений, а после сохранить ее и повторно загрузить модель и запустить predict, то выпадает ошибка: AttributeError: 'Sequential' object has no attribute 'num_classes' (у trained_model нет поляnum_classes ) и нужно каждый раз заново обучать модель, а не использовать готовую
Изучив проблему, я понял, что мы можем брать num_classes не только из trained_model, а еще из predict_data. При этом все это нужно обернуть в try catch, чтобы мы взяли num_classes из predict_data только тогда, когда в trained_model нет поля num_classes
Код который использовался для тестирования https://github.com/aimclub/FEDOT/blob/master/examples/simple/classification/image_classification_problem.py
После добавленных изменений модель можно загрузить и сделать …
> get predict_data.num_classes if trained_model havent num_classes

- examples/advanced/time_series_forecasting/exogenous.py
- examples/simple/time_series_forecasting/api_forecasting.py
- fedot/api/api_utils/api_params_repository.py
- fedot/core/data/data.py
- fedot/core/operations/evaluation/boostings.py
- fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
- fedot/core/operations/evaluation/operation_implementations/implementation_interfaces.py
- fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
- fedot/core/optimisers/objective/data_objective_eval.py
- fedot/core/pipelines/tuning/hyperparams.py
- fedot/utilities/ts_gapfilling.py
- test/integration/api/test_main_api.py
- test/integration/models/test_custom_model_introduction.py
- test/integration/pipelines/tuning/test_pipeline_tuning.py
- test/integration/quality/test_quality_improvement.py
- test/integration/real_applications/test_examples.py
- test/integration/real_applications/test_model_result_reproducing.py
- test/integration/remote/test_remote_composer.py
- test/integration/utilities/test_pipeline_import_export.py
- test/integration/utilities/test_project_import_export.py
- test/integration/validation/test_table_cv.py
Rework of integration tests passing.
> Integration tests fix v2

- .github/workflows/unit-build.yml
Add the ability to manually run unit tests using github actions
>  Running unit tests manually

- examples/simple/time_series_forecasting/api_forecasting.py
- fedot/core/repository/data/default_operation_params.json
- test/integration/models/test_model.py
- test/integration/real_applications/test_examples.py
1. Изменение дефолтного окна для `sparse_lagged`
2. Разбиение `test_api_example` на 4 отдельных теста
3. Изменение данных в `test_api_ts_forecasting_example` с `australia` на `test_sea`, т.к. последний вариант в несколько раз длиннее
4. Чуть более информативная ошибка в `test_models_does_not_fall_on_constant_data`
5. Исключение `cgru` из `test_models_does_not_fall_on_constant_data`
> Hotfix for integration tests

- .github/workflows/autopep8.yml
- .github/workflows/fix-pep8-command.yml
- .github/workflows/slash-command-dispatch.yml
**Requires** personal access token with repo scope.
Checks Python code with autopep8 on every commit.
Leaves a comment and updates it.
If you put `/fix-pep8` in the comments of the pull request, it will automatically fix all PEP8 bugs and push that commit into your PR.
If successful, it will leave a comment with the text "Fixed PEP8 problems!"
Example: https://github.com/DRMPN/FEDOT/pull/17
Resolves: https://github.com/aimclub/FEDOT/issues/1191
> Add automated code formatter

- .github/workflows/slash-command-dispatch.yml
Changing permission to execute `/fix-pep8` command from default write to read.
In PR #1244 code formatter didn't work. 
Received GitHub [action error](https://github.com/aimclub/FEDOT/actions/runs/7472825751): 
_Request failed due to following response errors: - You do not have permission to view repository collaborators._
> Change permission to read for pep8 code formatter

- .github/workflows/autopep8.yml
- .github/workflows/slash-command-dispatch.yml
Fix bug with permission to execute `/fix-pep8` command from read to none.
Change trigger from push to pull request. This fixes pep8 action false start before PR is even created.
PR #1244
> Fix code formatter bugs

- fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
- fedot/core/pipelines/tuning/search_space.py
- other_requirements/extra.txt
> fix sporadic forecasting test failure

- fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py
- test/unit/data_operations/test_data_operation_params.py
fixed [integration test](https://github.com/aimclub/FEDOT/blob/0bdece11af60d6e9abc84a894ddd66ea960b5611/test/integration/real_applications/test_examples.py#L86-L88) failure with: `ValueError: Found array with 0 feature(s) (shape=(3, 0)) while a minimum of 1 is required by check_pairwise_arrays.`
> add validation on _window_size param in topo extractor

- .github/workflows/unit-build.yml
Update codecov github action version from 1 to 4 (latest)
Tests failures in https://github.com/aimclub/FEDOT/pull/1287 and https://github.com/aimclub/FEDOT/pull/1288 due to codecov error
> Update version of codecov action

- other_requirements/extra.txt
- requirements.txt
This is a 🐛 bug fix
Fix gensim problem with pinned dependencies versions
PyPi intermediate release 0.7.3.2 doesn't publish:
```
Can't have direct dependency: gensim@                                  
git+https://github.com/piskvorky/gensim.git@ad68ee3 ; extra == "extra".
```
https://github.com/aimclub/FEDOT/actions/runs/8849483743/job/24301597093
> Fix gensim for PyPi release

- fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
- fedot/core/repository/data/model_repository.json
> fix: NaNs containing forecast on some ets configs

- fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
- fedot/core/operations/evaluation/operation_implementations/implementation_interfaces.py
This PR aims to fix the `ValueError: array must not contain infs or NaNs` for pipelines with `fast_ica` node.
Context and reproducibility steps:
closes #1293
> fix: NaNs containing data on fit stage for fast_ica

- fedot/api/api_utils/assumptions/assumptions_handler.py
- fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
- fedot/utilities/memory.py
- test/unit/pipelines/test_pipeline.py
Related to `api_ts_forecasting_example` integration test failure.
related to #1297, but not closing it since there are various types of troubled pipelines
closes #1300
> fix: go for forecast method instead of predict in ets

- fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
This is a :fire: hotfix.
related to https://github.com/aimclub/FEDOT/actions/runs/9499709347 integration workflow failure
related to #1297
> fix: indexing and seasonal_periods check that endog is at least twice the size

- fedot/api/api_utils/api_composer.py
- fedot/api/time.py
- test/integration/api/test_api_utils.py
- test/integration/api/test_main_api.py
- test/unit/optimizer/test_external.py
Now estimation is cv_folds-aware.
> Hotfix of fit time estimation for initial assumption

- fedot/core/data/data_split.py
- test/unit/data/test_data_split.py
This is a 🐛 bug fix. 
There was not enough copying for encoded categorical features during data spliting.
Fixes #1296
> Fix for #1296

- fedot/api/main.py
This is a 🙋 feature or enhancement.
related to discussion in #1298
> hotfix: go for FeaturesType instead of InputData in a pipeline tuning

- fedot/api/api_utils/presets.py
- fedot/core/operations/evaluation/boostings.py
- fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
- fedot/core/pipelines/tuning/search_space.py
- fedot/core/repository/data/default_operation_params.json
- fedot/core/repository/data/model_repository.json
- test/integration/api/test_api_utils.py
- test/unit/api/test_assumption_builder.py
- test/unit/api/test_presets.py
- test/unit/data_operations/test_time_series_operations.py
Реализован интерфейс fit/predict в родительском классе FedotXGBoostImplementation
<details>
<summary>Код</summary>
```py
class FedotXGBoostImplementation(ModelImplementation):
__operation_params = ['n_jobs', 'use_eval_set']
def __init__(self, params: Optional[OperationParameters] = None):
super().__init__(params)
self.model_params = {k: v for k, v in self.params.to_dict().items() if k not in self.__operation_params}
self.model = None
def fit(self, input_data: InputData):
input_data = input_data.get_not_encoded_data()
if self.params.get('use_eval_set'):
train_input, eval_input = train_test_data_setup(input_data)
train_input = self.convert_to_dataframe(train_input)
eval_input = self.convert_to_dataframe(eval_input)
train_x, train_y = train_input.drop(columns=['target']), …
```
> Boosting method implementation (XGBoost)

- docs/source/introduction/fedot_features/automation_features.rst
- test/integration/api/test_main_api.py
- test/integration/models/test_model.py
- test/integration/real_applications/test_heavy_models.py
This is a 🙋 feature or enhancement.
fixes #1240
fixes recent [integration tests failure](https://github.com/aimclub/FEDOT/actions/runs/10123551790/job/27996942320)
> fix: bring back cgru integration tests

- fedot/core/operations/evaluation/boostings.py
- fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
- fedot/core/pipelines/tuning/search_space.py
- fedot/core/repository/data/default_operation_params.json
- fedot/core/repository/data/model_repository.json
Реализован интерфейс fit/predict в родительском классе FedotLightGBMtImplementation
<details>
<summary>Код</summary>
```py
class FedotLightGBMImplementation(ModelImplementation):
__operation_params = ['n_jobs', 'use_eval_set']
def __init__(self, params: Optional[OperationParameters] = None):
super().__init__(params)
self.model_params = {k: v for k, v in self.params.to_dict().items() if k not in self.__operation_params}
self.model = None
def fit(self, input_data: InputData):
input_data = input_data.get_not_encoded_data()
if self.params.get('use_eval_set'):
train_input, eval_input = train_test_data_setup(input_data)
train_input = self.convert_to_dataframe(train_input)
eval_input = self.convert_to_dataframe(eval_input)
train_x, train_y = train_input.drop(columns=['target']), …
```
> Boosting method implementation (LightGBM)

- fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
fixes failed integration test runs:
- https://github.com/aimclub/FEDOT/actions/runs/10182025628/job/28163567768
- https://github.com/aimclub/FEDOT/actions/runs/10198420178/job/28213283039
> hotfix: boostings related failure of test_*_models_check_fit_predict_correct

- fedot/core/operations/evaluation/operation_implementations/data_operations/text_preprocessing.py
This is a 🐛 bug fix. 
fixes recent integration tests failures:
https://github.com/aimclub/FEDOT/actions/runs/10339781677
> hotfix: add punkt_tab to nltk LookupError check

- fedot/core/operations/evaluation/operation_implementations/data_operations/text_preprocessing.py
- other_requirements/extra.txt
related to https://github.com/nltk/nltk/issues/3293
> hotfix: pin nltk version to avoid downloading punkt_tab

- fedot/api/api_utils/predefined_model.py
- fedot/api/main.py
- test/integration/api/test_main_api.py
Quick Fix: prevent launch pipeline composition for Atomized model.
Example notebook with Atomized Model works as expected:
https://github.com/aimclub/FEDOT/blob/master/examples/advanced/additional_learning.py
Fixes #1317
> fix: do not launch composition for atomized model

- docs/source/benchmarks/forecasting.rst
- docs/source/benchmarks/img_benchmarks/cd-daily-m4-forecasting.svg
- docs/source/benchmarks/img_benchmarks/cd-monthly-m4-forecasting.svg
- docs/source/benchmarks/img_benchmarks/cd-overall-m4-forecasting.svg
- docs/source/benchmarks/img_benchmarks/cd-quarterly-m4-forecasting.svg
- docs/source/benchmarks/img_benchmarks/cd-weekly-m4-forecasting.svg
- docs/source/benchmarks/img_benchmarks/cd-yearly-m4-forecasting.svg
This is a 🔦 documentation change.
To demonstrate that the metrics of `FEDOT`, `Autogluon`, and `NBEATS` are indistinguishable, it's necessary to display critical difference diagrams for each season of the M4 benchmark.
> docs: add cd diagrams for m4 forecasting benchmark

- fedot/api/api_utils/api_composer.py
This is a 🔨 code refactoring
Initial pipeline fit time was displayed  in log as real fit time multiplied by _cv_folds_ (_cv_folds_ times longer)
Initial assumption fit time estimation is correct (takes into account _cv_folds_)
Added a message to log which clarifies initial assumption fit time estimation
Closes #1332
> Added a log message to clarify initial assumption fit time estimation

- .github/workflows/autopep8.yml
Should fix lack of datetime in GitHub action for pep8 bot.
Preview:
Text example in https://github.com/DRMPN/FEDOT/pull/22
Fixes #1306
> fix: Fix "last updated" date for edited PEP8 Action comment

- .github/workflows/notify.yml
Fixes formatting errors in Telegram notification messages.
Additionally:
- Changes the notification text.
- Removes the PR close notification.
Example:
Fixes #1347
> fix: Telegram PR merge notification

- test/integration/composer/test_composer.py
- test/integration/pipelines/tuning/test_pipeline_tuning.py
- test/integration/pipelines/tuning/test_tuner_builder.py
- test/integration/real_applications/test_examples.py
Fix for 
2024-12-27T22:51:08.1267941Z ##[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
2024-12-27T22:51:09.4060456Z /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/joblib/externals/loky/backend/resource_tracker.py:314: UserWarning: resource_tracker: There appear to be 10 leaked semlock objects to clean up at shutdown
2024-12-27T22:51:09.4061652Z   warnings.warn(
2024-12-27T22:51:09.4062683Z /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/joblib/externals/loky/backend/resource_tracker.py:314: UserWarning: resource_tracker: There appear to be 214 leaked folder objects to clean up at shutdown
2024-12-27T22:51:09.4063776Z   warnings.warn(
> Int test fix

- fedot/core/operations/evaluation/boostings.py
- fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
- test/integration/pipelines/tuning/test_pipeline_tuning.py
- test/unit/api/test_assumption_builder.py
- test/unit/preprocessing/test_preprocessing_through_api.py
**Failing test handling**
1. `FAILED AssertionError: assert 13 == ((5 * 2) - 1)`:
`assert mm_pipeline.length == mm_pipeline.depth * len(mm_data) - 1  # minus final ensemble` works well with length and depth of default initial assumption (scaling + rf). When the graph length increased, this assert does not work.
2. `FAILED Currently only multi-regression, multilabel and survival objectives work with multidimensional target.`:
Because of `convert_to_dataframe` method in boosting implementations, when trying to ravel array with multi-target (length of arrays 'train' and 'target' doesnt match). And catboost default parameter `"loss_function"` is `Logloss` instead of `MultiLogloss` (or `MultiRMSE` in regression tasks).
3. `FAILED test #0 contains class label "0" that is …
> Fix tests and add multi-target output for boostings

- fedot/core/data/data.py
This is a 🐛 bug fix. 
closes #1361
> hotfix: change parameters order in data conversion function signatures

- requirements.txt
Видимо тесты попадали из-за новой версии scikit-learn, пока ограничил <1.6
> Hotfix: pin scikit-learn version to <1.6

- requirements.txt
This hotfix resolves the problem of conflicting dependencies in a virtual environment created using poetry during the most recent [Fedot.Industrial workflow](https://github.com/aimclub/Fedot.Industrial/actions/runs/13543064825/job/37848288836):
```
Failed to clone https://github.com/aimclub/GOLEM.git at '45215bf', verify ref exists on remote.
```
> chore: bump up golem dependency version

- fedot/core/data/data.py
Refactored data.py:
- methods `from_numpy`, `from_dataframe`, `array_to_input_data` no longer require `target` parameter and can now accept `target=None`
- methods `subset_range`, `subset_indices` can correctly handle `target=None` option
> Refactor data handling: support optional target in all methods

- fedot/preprocessing/data_types.py
This small PR resolves the following two annoying warnings coming from `fedot/preprocessing/data_types.py`: 
```python
/tmp/FEDOT/fedot/preprocessing/data_types.py:425: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
.apply(pd.value_counts, dropna=False)
/tmp/FEDOT/fedot/preprocessing/data_types.py:106: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
if empty_columns:
```
> Fix warnings in data types

- examples/simple/classification/api_classification.py
- test/integration/cache/test_cache_parallel.py
This is a 🐛 bug fix. 
* Add option to enable/disable baseline model fitting for classification examples
* Lower timeout thresholds for regression and time series forecasting tests (retains original timeout for classification)
Attempt to resolve an occasionally timeout error.
```
2025-04-30T14:06:29.3589298Z =========================== short test summary info ============================
2025-04-30T14:06:29.3590938Z FAILED test/integration/cache/test_cache_parallel.py::test_parallel_cache_files - statsmodels.tools.sm_exceptions.ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
2025-04-30T14:06:29.3592580Z ===== 1 failed, 427 passed, 2 skipped, 5911 warnings in 4597.98s (1:16:37) =====
```
> hotfix: fix `parallel_cache_files` timeout error

- fedot/core/operations/evaluation/boostings.py
- fedot/core/operations/evaluation/evaluation_interfaces.py
- fedot/core/operations/evaluation/operation_implementations/implementation_interfaces.py
- fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
- fedot/core/utils.py
Multi-target classification fails during the `.predict()` operation if the input data lacks a target column. To address this, the multi-output mode state is now stored as a dynamically added in the `ModelImplementation` class. This allows the output behavior to be controlled via a model property rather than inferred from input data.
Fixes #1391
> fix: multi-target prediction without target in InputData
