core/composer/gp_composer/gp_composer.py
core/composer/optimisers/gp_optimiser.py
core/composer/visualisation.py
core/composer/write_history.py
core/log.py
core/utils.py
test/test_utils.py

- Изменен путь для default_logger
- Изменен путь для сохранения history.csv и визуализации в путь home/composing_history
- В export/import module [такие](https://github.com/nccr-itmo/FEDOT/blob/129_model-structure-to-JSON/utilities/synthetic/get_application_settings_path.py) пути используются для за-fit-ченных моделей (решение близкое к предложенному в issue). Дефолтных путей для json файлов не предусмотрено, обязательно надо передавать.

default home path

---

cases/credit_scoring_problem.py
examples/forecasting_model_composing.py
examples/multiclass_prediction.py
fedot/core/composer/chain.py
fedot/core/composer/composer.py
fedot/core/composer/gp_composer/fixed_structure_composer.py
fedot/core/composer/gp_composer/gp_composer.py
fedot/core/composer/iterator.py
fedot/core/composer/optimisers/crossover.py
fedot/core/composer/optimisers/gp_operators.py
fedot/core/composer/optimisers/gp_optimiser.py
fedot/core/composer/optimisers/inheritance.py
fedot/core/composer/optimisers/mutation.py
fedot/core/composer/optimisers/param_free_gp_optimiser.py
fedot/core/composer/optimisers/selection.py
fedot/core/composer/timer.py
fedot/core/composer/visualisation.py
fedot/core/composer/write_history.py
fedot/core/repository/data/model_repository.json
test/chain/test_node_cache.py
test/composer/test_composer.py
test/composer/test_selection_operators.py
test/models/test_split_train_test.py
test/models/test_tuning.py
test/tasks/test_clustering.py
test/tasks/test_regression.py
test/test_builder.py
test/test_iterator.py

Была добавлена схема схема эволюции называемая "parameter free" при которой такие параметры как размер популяции, размер потомства и кол-во поколений изменяются в ходе эволюции в зависимости от качества популяции, полученного на предыдущем шаге. Данная схема была вынесена в отдельный оптимайзер поскольку из-за этого код основного gp_optimiser стал загруженным.
Подробнее про схему эволюции можно почитать в этой статье: https://www.researchgate.net/publication/338883598_An_Adaptive_and_Near_Parameter-free_Evolutionary_Computation_Approach_Towards_True_Automation_in_AutoML.
Добавлена так же автоматическая настройка глубины дерева в ходе эволюции.
Помимо этого в  ходе стажировки стажером было обнаружена следующая ошибка: Если мы берем ранее обученную цепочку в моделях которой уже имеется …

Parameter free evo approach

---

fedot/core/composer/gp_composer/gp_composer.py
fedot/core/composer/optimisers/gp_optimiser.py
fedot/core/composer/optimisers/param_free_gp_optimiser.py

Исправлена ошибка неправильного вывода информации о количестве поколений в течении которых не было никаких улучшений.

fixed bug in stagnation output information

---

.github/workflows/publish_pypi.yml
fedot/core/composer/chain.py
fedot/core/composer/composer.py
fedot/core/composer/gp_composer/gp_composer.py
fedot/core/composer/node.py
fedot/core/composer/optimisers/gp_optimiser.py
fedot/core/composer/optimisers/param_free_gp_optimiser.py
fedot/core/log.py
fedot/core/models/model.py
fedot/core/models/tuning/tuners.py
setup.py
test/test_logger.py

- Bug with 'too many log-objects' was fixed (see issue #184)
- Minor fix with GPComposer logging (see PR #201)

Release Fedot v.0.1.2

---

fedot/core/models/evaluation/data_evaluation.py

Bug fixed: the PCA extracts N-1 features instead N features (and fails is is N==1)

PCA feature extraction bugfix

---

fedot/core/chain_validation.py
fedot/core/composer/gp_composer/gp_composer.py
fedot/core/composer/metrics.py
fedot/core/models/data.py
requirements.txt
setup.py

Fixes for chain composition for ts:
1. Sample split logic corrected
2. Metric calculation bug fixed

Ts composing fixes

---

fedot/utilities/synthetic/chain_template_new.py
test/utilities/test_chain_import_export.py

Closed #193
Устранил ошибку при работе с Node with model_type: "direct_data_model". Теперь не падает исключение.
При конвертации Chain -> ChainTemplate, количество нод и шаблонов моделей различалось, из-за модели с типом "direct_data_model". Так как я проверял равенство нод по свойству descriptive_id, а для моделей этого типа, свойство одинаковое.

193-bug_convertion-to-template

---

docs/source/fedot/utilities/chain_to_json.rst
fedot/core/chains/chain.py
fedot/core/chains/chain_template.py
fedot/core/chains/chain_tune.py
fedot/core/data/preprocessing.py
test/data/test_custom_json_template.json
test/data_operations/test_preprocessing.py
test/models/test_model.py
test/models/test_tuning.py
test/utilities/test_chain_import_export.py

Closed #207 
Исправил баги, кроме 3, не смог его воспроизвести.
Изменил структуру peprocessor для временных рядов.
Добавил логику для экспорта/импорта новое поле preprocess.
Рефакотинг ChainTemplate, ModelTemplates.
Добавил тест для проверки ScalingWithImputation.
Добавил логер.
Изменил логику сохранения моделей в формат:
05/29/2015 5:50:17 AM name_of_chain
- name_of_chain.json
- fitted_model
- model_1.pkl
- model_2.pkl
- model_3.pk
Изменил документацию.
Переписал тест для импорта\экспорта цепочки.

207 minor flaws

---

fedot/api/api_runner.py
test/tasks/test_api.py

api hotfix

---

fedot/core/composer/visualisation.py

Added directed acyclic graph visualization

added directed acyclic graph visualization

---

README.rst

The readme is actualized according to the https://actcognitive.org/platformy/freymvork-generativnogo-avtomaticheskogo-mashinnogo-obucheniya-fedot content: 
- text updated;
- obsolete links corrected
- several sections are moved
- new badges added

README actualized

---

README.rst
setup.py

1. Version updated to 0.2.1
2. API code in README actualized

Version updated to 0.2.1, README actualized

---

cases/credit_scoring_problem.py
fedot/core/chains/chain.py
fedot/core/chains/chain_template.py
fedot/core/chains/node.py
fedot/core/chains/ts_chain.py
fedot/core/composer/cache.py
fedot/core/composer/gp_composer/gp_composer.py
fedot/core/composer/optimisers/regularization.py
fedot/core/models/evaluation/data_evaluation.py
fedot/core/models/model_template.py
fedot/utilities/synthetic/chain_template.py
requirements.txt
test/unit/chains/test_chain.py
test/unit/chains/test_chain_tuning.py
test/unit/chains/test_node_cache.py

- cache moved from memory to disk using shelve library
- caching removed from nodes, now it is external object that can be used to 'fit' the nodes from pre-saved results

Better implementation of the caching

---

examples/multiclass_prediction.py

Added an exception for importing "pyopenxl" library to avoid the over-complicated requirements.txt. Fix for #254.

Added exception for lack of openpyxl library

---

test/unit/test_utils.py

test_fedot_project_root function added it tests as subtask to refactoring the directory (issue #258 )

Test for fedot_project_root

---

cases/credit_scoring_problem_multiobj.py
fedot/api/api_utils.py
fedot/api/main.py
fedot/core/chains/chain.py
fedot/core/chains/chain_template.py
fedot/core/composer/composing_history.py
fedot/core/composer/optimisers/gp_comp/gp_operators.py
fedot/core/composer/optimisers/gp_comp/gp_optimiser.py
fedot/core/composer/optimisers/gp_comp/individual.py
fedot/core/composer/optimisers/gp_comp/operators/crossover.py
fedot/core/composer/optimisers/gp_comp/operators/mutation.py
fedot/core/composer/optimisers/gp_comp/operators/regularization.py
fedot/core/composer/optimisers/gp_comp/operators/selection.py
fedot/core/composer/optimisers/gp_comp/param_free_gp_optimiser.py
test/unit/chains/test_chain.py
test/unit/composer/test_composer.py
test/unit/composer/test_gp_operators.py
test/unit/composer/test_history.py
test/unit/composer/test_selection_operators.py
test/unit/visualization/test_composing_history.py

- ParentOperator class is added in order to preserve the full history of each individual. 
- Now each individual has the parent_operators field that is exporting to the history.
- Individual class added to store fitness and parent_operators during evolution
It is required for the compability with future evolutionary vizualization in FEDOT.Web.

Evolutionary operators saving to composing history

---

README.rst

- link to TDS post
- link to new pre-print

New links added

---

examples/additional_learning.py
fedot/api/api_utils.py
fedot/core/operations/atomized_model.py
fedot/core/pipelines/pipeline.py
fedot/core/pipelines/validation_rules.py
test/unit/models/test_atomized_model.py

In this PR, the example of the additional learning impemented. Also, some atomization-related fixes were done.
The experiment consits of 3 steps:
1. Initial learning for first 1000 rows of data:
auto_model {'roc_auc': 0.834}
Best chain: 
2. Additional learning (first 5000 rows) for atomized best model as initial chain:
auto_model_from_atomized {'roc_auc': 0.848}
3. Additional learning (first 5000 rows) for non-atomized best model as initial chain:
auto_model_from_atomized {'roc_auc': 0.844}

Example of additional learning using atomization

---

fedot/core/operations/evaluation/evaluation_interfaces.py
fedot/core/operations/operation.py
test/unit/models/test_model.py

- The output of the catboost model is completely removed.
- The issue of default parameters for models has been resolved.

catboost default params changed

---

examples/time_series/ts_forecasting_composing.py
fedot/core/composer/gp_composer/specific_operators.py
fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
fedot/core/operations/operation.py
fedot/core/pipelines/node.py
fedot/core/pipelines/tuning/hyperparams.py
test/unit/composer/test_composer.py
test/unit/composer/test_mutation_params.py
test/unit/data_operations/test_time_series_operations.py

A new class ParametersChanger has been implemented, which allows to gradually change the hyperparameters of operations when composing a pipeline. 
Slightly changed default hyperparameters values for some operations.

Made incremental parameters change

---

README.rst
docs/source/conf.py
requirements.txt
setup.py

Version updated to 0.4.0, reqs simplisied

Version updated to 0.4.0, less strict requirements

---

fedot/api/api_utils.py
fedot/core/data/data.py
fedot/core/operations/operation_template.py
fedot/core/pipelines/template.py

* export bug fixed (pipeline_import_export.py was not working)
* additional preset added (required for FEDOT.Web integration)

Export and presets correction

---

examples/fedot_api_example.py
examples/pipeline_and_history_visualisation.py
fedot/api/api_utils.py
fedot/api/main.py
fedot/core/optimisers/gp_comp/gp_optimiser.py
fedot/core/optimisers/opt_history.py
fedot/core/pipelines/pipeline.py

* custom path for composer history added

Custom history path added

---

fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_selectors.py
test/unit/data_operations/test_data_operations_implementations.py

Fixed single feature selection

---

cases/credit_scoring/credit_scoring_problem.py
examples/time_series/ts_forecasting_with_exogenous.py
fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
fedot/core/repository/default_model_params_repository.py
test/integration/real_applications/test_real_cases.py
test/integration/test_profiler.py

Fixing bags in integral tests. Now only test_api_example sometimes fails with an error.

Bag fixing in integration tests

---

examples/time_series/ts_fitted_target.py
examples/time_series/ts_fitted_values.py
fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
fedot/core/pipelines/ts_wrappers.py
test/unit/pipelines/test_pipeline_ts_wrappers.py

Implemented different ways to get fitted values for time series. 
The idea is the same as fittedvalues method in ARIMA from statsmodels

Fitted values for time series

---

README.rst

Journal link instead arxiv, number of papers reduced

Paper references in README updated

---

fedot/core/optimisers/gp_comp/gp_operators.py
test/unit/composer/test_composer.py

Changes were made to random_graph() and a test for valid graph generation was added.

Fixes for issue #341

---

fedot/api/api_utils/presets.py
fedot/core/operations/operation_template.py
fedot/core/optimisers/adapters.py
fedot/core/pipelines/template.py
test/unit/pipelines/test_decompose_pipelines.py
test/unit/utilities/test_pipeline_import_export.py

- export of non-fitted pipelines to string fixed
- additional workaround for non-stable models
- node transformation workaround

Yet another FEDOT.web connection fix

---

README.rst

Changes:
- habr post link
- fedot web link
- minor fixes

Readme updated with new links

---

fedot/core/composer/gp_composer/specific_operators.py
fedot/core/dag/node_operator.py
fedot/core/optimisers/adapters.py
test/unit/optimizer/test_gp_operators.py

Modifications from #435  are implemented.  Additional variability is added to boosting mutation.

Boosting mutation corrected

---

test/unit/optimizer/test_selection_operators.py

Pipelines uniqueness enforced in 'rand_population_gener_and_eval'
Closes #439

Selection test fixed

---

cases/pennml_check.py
fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
fedot/core/operations/evaluation/operation_implementations/models/discriminant_analysis.py
fedot/core/pipelines/pipeline.py
fedot/core/pipelines/preprocessing.py

Solving errors in `_preprocessing_input_data()` and `ImputationImplementation - fit`. Was added method `preprocessing_features_full_of_nans()` in preprocessing.py, which dropping features with more than 30% of nan's. Fix problem in `sklearn_transformation.py`.

Editing preprocessing

---

cases/pennml_check.py
fedot/core/pipelines/pipeline.py
fedot/core/pipelines/preprocessing.py

Was created DataProcessing class which contains functions for data preprocessing

Wrap data proccessing into class

---

fedot/core/operations/evaluation/operation_implementations/models/knn.py
test/unit/data_operations/test_data_operations_implementations.py

Now the integer values of the hyperparameter n_neighbors for the K-nn model are rounded to integers

Fix K-nn model

---

examples/time_series/ts_fitted_values.py
fedot/core/pipelines/ts_wrappers.py

Corrected the calculation of fitted values with new indices

Fitted time series fix

---

requirements.txt

Fix imageio version  imageio>=2.8,<=2.10

imageio version fix

---

examples/fedot_api_example.py
fedot/api/api_utils/api_composer.py
fedot/api/api_utils/params.py
fedot/core/composer/gp_composer/gp_composer.py
fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_imbalanced_class.py
fedot/core/optimisers/gp_comp/gp_optimiser.py
fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
fedot/core/pipelines/node.py
fedot/core/pipelines/validation_rules.py
fedot/core/repository/operation_types_repository.py
test/unit/composer/test_composer.py

Resolve the issue [#445](https://github.com/nccr-itmo/FEDOT/issues/445). 
The stopping criteria should be implemented for a composer to avoid unnecessary long runs. The proposed criteria is 'N generations without improvement' for all objective functions. Default `stopping_after_n_generation = 7`, but the external configuration option should be provided.

Stopping criteria for composer

---

fedot/core/operations/evaluation/common_preprocessing.py
fedot/core/operations/evaluation/operation_implementations/data_operations/categorical_encoders.py
fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
fedot/core/repository/data/data_operation_repository.json
fedot/preprocessing/preprocessing.py
test/unit/data_operations/test_data_operations_implementations.py
test/unit/models/test_model.py

Added LabelEncoder Implementation for future works with DataAnalyser module. Encoders were a little bit refactored

Implement Label Encoder

---

examples/data/beer.csv
examples/time_series/derivative_example.py
examples/time_series/polyfit_example.py
fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
fedot/core/operations/evaluation/time_series.py
fedot/core/pipelines/tuning/search_space.py
fedot/core/repository/data/data_operation_repository.json
fedot/core/repository/data/default_operation_params.json

Implementation of method to finding a numerical derivative of time series

NumericalDerivativeImplementation implementation

---

cases/multi_modal_rating_prediction.py
cases/river_levels_prediction/river_level_case_composer.py
examples/advanced/additional_learning.py
examples/advanced/time_series_forecasting/composing_pipelines.py
examples/simple/time_series_forecasting/ts_pipelines.py
examples/simple/time_series_forecasting/tuning_pipelines.py
fedot/api/api_utils/api_composer.py
fedot/api/api_utils/initial_assumptions.py
fedot/api/main.py
fedot/core/composer/composer.py
fedot/core/composer/composer_builder.py
fedot/core/composer/gp_composer/gp_composer.py
fedot/core/composer/random_composer.py
fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
fedot/core/optimisers/gp_comp/gp_operators.py
fedot/core/optimisers/gp_comp/gp_optimiser.py
fedot/core/pipelines/template.py
fedot/core/pipelines/tuning/hyperparams.py
test/unit/api/test_api_utils.py
test/unit/api/test_main_api.py
test/unit/composer/test_composer.py
test/unit/models/test_custom_model_introduction.py
test/unit/validation/test_time_series_cv.py

Due of increasing number of time series forecasting models number of initial assumptions was increased. 
List of initial assumptions for time series forecasting:
- glm + ridge pipeline
- polyfit + ridge  pipeline
- lagged + ridge pipeline
- ar pipeline

Increasing number of initial assumptions

---

docs/source/conf.py
setup.py

Preprocessing for tabular features and target variables improved dramatically.
API is refactored and improved (presets, parameters, etc). The postfix "_tun" has been removed from the presets, so now you have to specify composer_params={'with_tuning': True} to set tuning. Important changes in preset names: light - best_quality, ultra_light - fast_train.
Support for external optimisers is implemented.
Zero-code console interface is implemented .
Surrogate decision trees for pipeline interpretation are added.
Custom model support is implemented.
Better presets and models for time series forecasting (derivatives, polynomial models, cuts, etc)
Better integration with FEDOT.Web
Prototype for remote infrastructure support
Evolutionary optimiser improved (stopping criterion, progress bar, better …

Version updated to 0.5.0

---

fedot/core/pipelines/template.py

Fix for export of preprocessor from dictionary (required for FEDOT.Web)

Preprocessor export fixed

---

.gitignore
examples/simple/time_series_forecasting/api_foresacting.py
fedot/api/api_utils/api_composer.py
fedot/api/api_utils/params.py
fedot/api/main.py
fedot/preprocessing/preprocessing.py
test/unit/api/test_api_safety.py
test/unit/api/test_api_utils.py

* bug with predefined initial assumption was fixed
* bug with None as default value for cv_folds in api for ts_forecasting  was fixed

Fix initial assumption

---

Dockerfile_light
fedot/core/operations/evaluation/operation_implementations/models/keras.py
fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/clstm.py
light_requirements.txt

light_req.txt and light_dockerfile are added to reduce the size of container if necessary

Keras and TF moved to not mandatory requirements

---

examples/simple/time_series_forecasting/api_foresacting.py
fedot/api/api_utils/api_composer.py
fedot/core/composer/composer_builder.py
fedot/core/data/visualisation.py
test/unit/optimizer/test_external.py

With this pull-request we add ability to add external parameters for a custom optimizer

add ability to add external parameters for optimizer

---

fedot/core/pipelines/tuning/tuner_interface.py
test/unit/pipelines/test_pipeline_tuning.py

Changed logic to the comparison between optimal prediction and constant prediction.

Updated _is_greater_better logic

---

fedot/core/dag/graph_operator.py
test/unit/dag/test_graph_operator.py

Add get_all_edges method for GraphOperator

add get_all_edges method

---

cases/dataset_preparation.py
cases/multi_modal_genre_prediction.py
examples/multi_modal_pipeline_genres.py
fedot/core/data/data.py
fedot/core/data/data_split.py
fedot/core/data/merge.py
fedot/core/operations/evaluation/operation_implementations/data_operations/text_preprocessing.py
fedot/core/operations/evaluation/text.py
fedot/core/operations/model.py
fedot/core/repository/data/model_repository.json
requirements.txt

**multi_modal_genre_prediction**
Новый скрипт для задачи мультимодальной классификации жанров
**multi_modal_pipeline_genres**
Скрипт для генерации пайплайна на базе multi_modal_pipeline
**text_preprocessing**
Добавил lower case в предобработку
**data**
Добавил генерацию таргета для multilabel output

multimodal genre prediction

---

fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_imbalanced_class.py
fedot/core/pipelines/tuning/hyperparams.py
fedot/core/pipelines/tuning/search_space.py
fedot/core/repository/data/default_operation_params.json
requirements.txt

Minor corrections for the better user experience

Redunant warning removed, requirements updated

---

examples/advanced/multiobj_optimisation.py
fedot/api/api_utils/api_composer.py
fedot/core/composer/gp_composer/gp_composer.py
fedot/core/optimisers/gp_comp/gp_optimiser.py
fedot/preprocessing/data_types.py

Corrected Pareto front visualization, also made minor edits

Pareto front fix

---

fedot/api/api_utils/api_composer.py
fedot/core/validation/tune/tabular.py
fedot/utilities/define_metric_by_task.py

https://github.com/nccr-itmo/FEDOT/issues/559 
https://github.com/nccr-itmo/FEDOT/issues/560
The calculation of the time allocated for tuning hyperparameters has been changed, depending on the time that was actually spent on composing. Small changes in the calculation of the quality metric when tuning hyperparameters.

tuning time and metric score fixes

---

fedot/api/api_utils/api_data.py
fedot/api/main.py
fedot/core/pipelines/pipeline.py
fedot/preprocessing/preprocessing.py

Fixed setting indices for time series forecasting through API forecast method

Api forecast indices fix

---

README.rst
docs/source/conf.py
setup.py

- New release is published
- Readme is updated

Version updated to 051

---

fedot/api/api_utils/api_composer.py
fedot/api/api_utils/initial_assumptions.py
fedot/api/api_utils/presets.py
fedot/core/repository/data/model_repository.json
test/unit/api/test_presets.py

fixes in timeout for tuning calculation. XGBoost and Catboost was excluded from avaliable model list

tuning timeout and initial_assumptions fixes

---

examples/advanced/parallelization_comparison.py
examples/simple/time_series_forecasting/api_foresacting.py
fedot/api/api_utils/api_composer.py
fedot/api/main.py
fedot/core/composer/gp_composer/gp_composer.py
fedot/core/optimisers/gp_comp/evaluating.py
fedot/core/optimisers/gp_comp/gp_operators.py
fedot/core/optimisers/gp_comp/gp_optimiser.py
fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
fedot/core/optimisers/optimizer.py
fedot/core/pipelines/pipeline.py
fedot/core/validation/compose/tabular.py
test/unit/api/test_api_utils.py
test/unit/composer/test_composer.py
test/unit/pipelines/test_pipeline.py

Parallelization using multiprocessing.Pool for individuals was implemented

Implemented parallelization

---

fedot/core/operations/evaluation/common_preprocessing.py
fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
fedot/core/pipelines/tuning/search_space.py
fedot/core/repository/data/data_operation_repository.json

[ISSUE](https://github.com/nccr-itmo/FEDOT/issues/429)
@v1docq

Fast ICA implementation

---

fedot/core/optimisers/gp_comp/gp_optimiser.py
fedot/core/optimisers/opt_history.py
fedot/core/optimisers/optimizer.py

Disabling of runtime optimiser history saving implemented

Disabling of history saving implemented

---

fedot/api/api_utils/metrics.py
fedot/core/composer/metrics.py
fedot/core/repository/quality_metrics_repository.py

Added a new metric SMAPE that can be used for both tuner and composer

add SMAPE metric

---

fedot/api/main.py
test/unit/api/test_api_safety.py

There was a bug with preprocessing for final pipeline fitting. It doesn't apply any recommendation if we don't need to cut dataset in a safe mode.

fix bug with final fit

---

fedot/core/dag/graph_operator.py
fedot/core/operations/evaluation/operation_implementations/data_operations/categorical_encoders.py
fedot/preprocessing/categorical.py
test/unit/preprocessing/test_preprocessing_though_api.py

Earlier in `_apply_encoder` method new labels were recursively added to the `encoder.classes_` if they had not been encountered before. 
Now at the very beginning we go through the current column and add all the labels that have not been seen before

fix apply encoder method

---

examples/simple/regression/api_regression.py
fedot/api/api_utils/api_composer.py
fedot/api/main.py
fedot/api/time.py
fedot/core/operations/operation.py
fedot/core/optimisers/gp_comp/gp_operators.py
fedot/core/optimisers/gp_comp/gp_optimiser.py
fedot/core/optimisers/gp_comp/operators/crossover.py
fedot/core/optimisers/gp_comp/operators/mutation.py
fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
fedot/core/optimisers/optimizer.py
fedot/core/pipelines/node.py
fedot/core/pipelines/pipeline.py
fedot/core/pipelines/template.py
fedot/core/repository/data/default_operation_params.json
fedot/core/validation/compose/time_series.py
test/unit/composer/test_composer.py
test/unit/composer/test_history.py
test/unit/validation/test_table_cv.py

- Initial assumptions and final results are added to the OptHistory.
- Bug with crossover fixed
- Bug with None timeout fixed
- Cache disabled for ts composing in multiprocessing mode

Extended optimizer history

---

examples/advanced/automl/h2o_example.py
examples/advanced/automl/tpot_example.py
fedot/core/operations/automl.py
fedot/core/repository/operation_types_repository.py

Issue https://github.com/nccr-itmo/FEDOT/issues/600 has been resolved in this PR

repaired automl examples

---

fedot/core/optimisers/gp_comp/evaluating.py

Computation time for the individual was not recorded

fix individual computation time

---

fedot/core/pipelines/pipeline.py
requirements.txt
test/unit/models/test_model.py
test/unit/pipelines/test_pipeline.py

func_timeout library is used to avoid multiprocessing overhead

Proposed improvement for fit_time constraint

---

fedot/core/optimisers/gp_comp/evaluating.py
fedot/core/pipelines/pipeline.py
test/unit/optimizer/test_gp_operators.py

Fix computation time for an individual is written to its metadata

fix individual computation time in metadata

---

examples/simple/classification/api_classification.py
examples/simple/time_series_forecasting/api_foresacting.py
fedot/api/api_utils/api_composer.py
fedot/api/main.py
fedot/core/composer/gp_composer/gp_composer.py
fedot/core/optimisers/adapters.py
fedot/core/optimisers/gp_comp/evaluating.py
fedot/core/optimisers/gp_comp/gp_operators.py
fedot/core/optimisers/gp_comp/gp_optimiser.py
fedot/core/optimisers/gp_comp/intermediate_metric.py
fedot/core/pipelines/node.py
fedot/core/pipelines/pipeline.py
fedot/core/pipelines/template.py
fedot/core/pipelines/tuning/search_space.py
fedot/core/repository/quality_metrics_repository.py
fedot/core/serializers/serializer.py
fedot/core/validation/metric_estimation.py
fedot/core/validation/split.py
test/unit/api/test_api_utils.py
test/unit/composer/test_composer.py
test/unit/composer/test_history.py
test/unit/optimizer/test_gp_operators.py
test/unit/validation/test_table_cv.py

Now such information about pipelines and nodes will saved:
1) fit time in seconds
2) inference time in second
3) metric for node if needed

Save additional info about nodes

---

fedot/core/optimisers/gp_comp/intermediate_metric.py
test/unit/composer/test_history.py

Bug with the same metric for all nodes was solved

Hotfix for PR #612

---

examples/simple/pipeline_and_history_visualisation.py
fedot/api/main.py
fedot/core/optimisers/gp_comp/gp_optimiser.py
fedot/core/optimisers/opt_history.py
fedot/core/visualisation/opt_viz.py

Add fintess visualization to API. Visualization can be done from already collected results from json file or from just obtained results

add fitness visualization to api

---

cases/multi_modal_genre_prediction.py
examples/advanced/multi_modal_pipeline.py
fedot/core/data/data.py
fedot/core/operations/evaluation/operation_implementations/models/keras.py
requirements.txt
test/unit/multimodal/test_multi_modal.py

- fixed occasional error of test_image_classification_quality
- added vgg16 architecture to models list
- image resize function now supports RGB images
- changed the format of image size to more сonvenient

Image processing improvement

---

examples/advanced/decompose/regression_refinement_example.py
examples/advanced/multitask_classification_regression.py
examples/simple/multitask_classification_regression_api.py
fedot/api/api_utils/data_definition.py
fedot/api/api_utils/metrics.py
fedot/api/main.py
fedot/core/data/multi_modal.py
test/unit/multimodal/test_multimodal.py
test/unit/tasks/test_multi_task.py

* Added new example with running multitask through API (it does not work and in this PR probably do not plan to fix it - for now this is an example of how I would like to apply data to the input)
* I added the ability to tune multimodal pipelines with multimodal data for multitask
* Redesigned the MultiModalData logic, so that this dataclass can be used for multitasking tasks with different target
* Prepared a prototype of how to run FEDOT on multimodal data via API (check tests)

Multitask and multimodal api improvements

---

fedot/core/validation/tune/tabular.py
test/unit/pipelines/test_pipeline_tuning.py

1. Added transformation to numpy array for multiclass
2. Added cross-testing of cross validation, pipelines and metrics
3. Separated search space tests

Added convertation of cv_tabular predictions to numpy array 

---

fedot/api/main.py
fedot/core/composer/cache.py
fedot/core/composer/cache_db.py
fedot/core/composer/composer_builder.py
fedot/core/dag/graph.py
fedot/core/dag/graph_operator.py
fedot/core/optimisers/graph.py
fedot/core/pipelines/template.py
fedot/core/utilities/data_structures.py
fedot/core/validation/metric_estimation.py
test/unit/test_utils.py

+ input sequence type prevention
+ optional sequence convertion type

generalized `ensure_list` to `ensure_wrapped_in_sequence`

---

fedot/core/operations/evaluation/evaluation_interfaces.py
fedot/core/operations/hyperparameters_preprocessing.py
fedot/core/operations/operation.py
fedot/core/pipelines/tuning/search_space.py
test/unit/pipelines/test_pipeline_tuning.py

1. Added HyperparametersPreprocessing class with integer converting and share from n_samples converting
2. Replaced choice search spaces

Added hyperparameters preprocessing

---

fedot/core/operations/hyperparameters_preprocessing.py
test/unit/pipelines/test_pipeline_tuning.py

1. Added le0_to_none preprocessig
2. Added preprocessing skip for None parameter values
3. Added test with max_depth equal to -1
4. Added preprocessing stop

Added le0_to_none preprocessing to hyperparameters preprocessing

---

README.rst

Links to posts devoted to FEDOT are updated.

Links in README are updated

---

examples/advanced/time_series_forecasting/composing_pipelines.py
examples/advanced/time_series_forecasting/multistep.py
examples/simple/time_series_forecasting/ts_pipelines.py
fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
fedot/core/pipelines/ts_wrappers.py
fedot/core/repository/data/model_repository.json
test/unit/dag/test_graph_operator.py

Before this pr such statsmodels models as Arima, STLArima, AuroReg had special flag "refit_insample" for refitting on a new data while insample forecasting. Now this logic moved into implementation for being able to use it not only in FEDOT insample forecasting method.

Update statsmodels models

---

fedot/core/optimisers/objective/data_objective_advisor.py
fedot/core/optimisers/objective/data_objective_builder.py
fedot/core/validation/split.py
test/unit/validation/test_table_cv.py

This pr solve https://github.com/nccr-itmo/FEDOT/issues/732 issue. DataObjectiveAdvisor was created to advise the most suitable strategy to split data on folds.

Embedding stratify k fold

---

fedot/api/api_utils/api_composer.py
fedot/api/api_utils/assumptions/assumptions_advisor.py
fedot/api/api_utils/assumptions/assumptions_builder.py
fedot/api/api_utils/assumptions/assumptions_handler.py
fedot/api/api_utils/predefined_model.py
fedot/api/api_utils/presets.py
fedot/api/main.py
fedot/api/time.py
fedot/core/composer/composer_builder.py
fedot/core/pipelines/tuning/search_space.py
test/unit/api/test_api_utils.py
test/unit/api/test_assumption_builder.py
test/unit/validation/test_table_cv.py
test/unit/validation/test_time_series_cv.py

This PR is devoted to https://github.com/nccr-itmo/FEDOT/issues/717 issue and separate logic for initial assumption from api composer

Extract fit initiall assumption#717

---

fedot/core/composer/composer.py
fedot/core/composer/composer_builder.py
fedot/core/composer/gp_composer/specific_operators.py
fedot/core/optimisers/gp_comp/gp_operators.py
fedot/core/optimisers/gp_comp/gp_optimiser.py
fedot/core/optimisers/gp_comp/operators/mutation.py
fedot/core/optimisers/opt_node_factory.py
fedot/core/optimisers/optimizer.py
fedot/core/pipelines/pipeline_graph_generation_params.py
fedot/core/pipelines/pipeline_node_factory.py
test/unit/composer/test_composer.py
test/unit/composer/test_history.py
test/unit/optimizer/test_default_node_factory.py
test/unit/optimizer/test_gp_operators.py
test/unit/optimizer/test_selection_operators.py
test/unit/pipelines/test_pipeline_node_factory.py
test/unit/tasks/test_custom.py

Mutation operators now are not specific for AutoML (Pipeline). All operations for creating new nodes while mutation are incapsulated in OptNodeFactory abstract class and can be implemented specifically for any other task.
#727

706 node factory mutation

---

cases/credit_scoring/credit_scoring_problem.py
cases/metocean_forecasting_problem.py
examples/advanced/additional_learning.py
examples/advanced/fedot_based_solutions/external_optimizer.py
examples/advanced/parallelization_comparison.py
examples/simple/regression/api_regression.py
fedot/api/api_utils/api_composer.py
fedot/api/api_utils/assumptions/assumptions_handler.py
fedot/api/api_utils/params.py
fedot/api/main.py
fedot/core/log.py
fedot/core/operations/evaluation/operation_implementations/models/keras.py
fedot/core/optimisers/gp_comp/gp_optimiser.py
test/integration/api_params/test_main_api_params.py
test/integration/quality/test_quality_improvement.py
test/integration/quality/test_synthetic_tasks.py
test/unit/api/test_api_utils.py
test/unit/api/test_main_api.py
test/unit/models/test_custom_model_introduction.py
test/unit/optimizer/test_external.py
test/unit/validation/test_table_cv.py
test/unit/validation/test_time_series_cv.py

Rename verbose_level to logging_level since the logic for specifying the level of detail has been changed. Also fixed compatibility logging levels with tensotflow verbose

777 logger ignores versbosity in linux

---

fedot/core/composer/gp_composer/specific_operators.py
fedot/core/optimisers/gp_comp/gp_optimiser.py
fedot/core/optimisers/gp_comp/operators/mutation.py
test/unit/composer/test_composer.py
test/unit/composer/test_history.py
test/unit/optimizer/test_gp_operators.py
test/unit/optimizer/test_selection_operators.py
test/unit/validation/test_table_cv.py

Mutation functions are wraped in a Mutation class. 
#706

Mutation operator

---

fedot/core/composer/composer.py
fedot/core/composer/composer_builder.py
fedot/core/composer/gp_composer/gp_composer.py
fedot/core/composer/random_composer.py
fedot/core/optimisers/gp_comp/operators/operator.py
fedot/core/optimisers/objective/__init__.py
fedot/core/optimisers/objective/data_objective_builder.py
fedot/core/optimisers/objective/data_source_builder.py
test/unit/composer/test_builder.py
test/unit/composer/test_composer.py
test/unit/composer/test_history.py
test/unit/data/test_data_split.py
test/unit/optimizer/test_gp_operators.py

Minor PR. Now this class only determines how to split the data (holdout, kfold or no split).
Few more minor refactorings.

Simplify & rename DataObjectiveBuilder

---

fedot/api/main.py
fedot/core/repository/data/default_operation_params.json
test/unit/api/test_api_safety.py

Touched https://github.com/nccr-itmo/FEDOT/issues/782 issue and https://github.com/nccr-itmo/FEDOT/issues/775 issue

Fix pca math domain error

---

cases/credit_scoring/credit_scoring_problem_multiobj.py
fedot/core/composer/composer_builder.py
fedot/core/composer/gp_composer/gp_composer.py
fedot/core/data/data.py
fedot/core/optimisers/objective/__init__.py
fedot/core/optimisers/objective/data_source_builder.py
fedot/core/optimisers/objective/data_source_splitter.py
fedot/core/optimisers/opt_history.py
fedot/core/optimisers/opt_node_factory.py
fedot/core/optimisers/optimizer.py
fedot/core/pipelines/pipeline_graph_generation_params.py
fedot/preprocessing/preprocessing.py
test/unit/composer/test_composer.py
test/unit/composer/test_history.py
test/unit/data/test_data_split.py
test/unit/optimizer/test_gp_operators.py

- Added possibility to save OptHistory to any directory (not just default fedot dir)
- Added possibility to change Composer implementation class
- Added possibility to set GraphGenerationParams in ComposerBuilder
- Rename `DataSourceBuilder` to `DataSourceSplitter` which better reflects its function
- Add `split_ratio` & `shuffle` parameters to `DataSourceSplitter`

Minor ComposerBuilder fixes for NAS

---

fedot/core/operations/operation_template.py
fedot/core/pipelines/template.py

fixes #760 
Problem was with incorrect usage of BytesIO object

Fix incorrect loading of preprocessing in PipelineTemplate

---

fedot/core/caching/pipelines_cache_db.py
fedot/core/log.py
fedot/core/optimisers/composer_requirements.py

Fixes [this issue](https://github.com/nccr-itmo/FEDOT/issues/815)

815-tmp-already-exists

---

fedot/core/composer/gp_composer/specific_operators.py
test/unit/optimizer/test_gp_operators.py

Fix for issue https://github.com/nccr-itmo/FEDOT/issues/778. Checks on available operations in mutation were deleted.

Fix boosting mutations

---

test/unit/api/test_presets.py

Fix of #827 issue. The timeout is decreased.

Hotfix of #827 test_auto_preset_converted_correctly fails

---

fedot/core/optimisers/gp_comp/gp_optimizer.py
fedot/core/optimisers/populational_optimizer.py

catch AttributeError when composing stopped

---

fedot/core/optimisers/objective/data_objective_eval.py

https://github.com/nccr-itmo/FEDOT/issues/834 
Forgot about unfitting pipelines after fold evaluation and that causes problems again

Hotfix for refactoring-preprocessing

---

fedot/core/operations/evaluation/evaluation_interfaces.py
fedot/core/pipelines/tuning/search_space.py
fedot/core/repository/data/default_operation_params.json
requirements.txt

Resolve https://github.com/nccr-itmo/FEDOT/issues/844 issue. Rename params and drop num_threads param

Remove lgbm logs

---

examples/simple/classification/multiclass_prediction.py
fedot/api/api_utils/assumptions/assumptions_builder.py
fedot/api/api_utils/presets.py
fedot/api/help.py
fedot/core/composer/gp_composer/specific_operators.py
fedot/core/data/supplementary_data.py
fedot/core/operations/evaluation/evaluation_interfaces.py
fedot/core/operations/evaluation/gpu/classification.py
fedot/core/operations/evaluation/gpu/clustering.py
fedot/core/operations/evaluation/gpu/common.py
fedot/core/operations/evaluation/gpu/regression.py
fedot/core/pipelines/verification_rules.py
fedot/core/repository/operation_types_repository.py
fedot/sensitivity/node_sa_approaches.py
test/unit/api/test_assumption_builder.py
test/unit/api/test_presets.py
test/unit/composer/test_builder.py
test/unit/composer/test_composer.py
test/unit/data_operations/test_data_operations_implementations.py
test/unit/models/test_model.py
test/unit/models/test_repository.py
test/unit/optimizer/test_gp_operators.py
test/unit/validation/test_table_cv.py

- [Fixed] List of models for GPU present was not obtaining correctly
- [Added] Test for GPU preset
Example of solved problem:

GPU preset fix

---

cases/multivariate_ts_forecasting.py
fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
fedot/core/optimisers/objective/data_source_splitter.py
fedot/core/pipelines/tuning/search_space.py

Fix for https://github.com/nccr-itmo/FEDOT/issues/734 issue. Some types of GL models were deleted due to instability

Glm bug fix

---

examples/simple/classification/api_classification.py
fedot/api/api_utils/params.py
fedot/core/caching/pipelines_cache.py
fedot/core/caching/preprocessing_cache.py
fedot/core/operations/evaluation/classification.py
fedot/core/operations/evaluation/clustering.py
fedot/core/operations/evaluation/common_preprocessing.py
fedot/core/operations/evaluation/evaluation_interfaces.py
fedot/core/operations/evaluation/gpu/clustering.py
fedot/core/operations/evaluation/gpu/common.py
fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
fedot/core/operations/evaluation/regression.py
fedot/core/optimisers/objective/data_objective_eval.py
fedot/core/pipelines/pipeline.py
fedot/core/pipelines/template.py
fedot/core/utilities/random.py
fedot/utilities/debug.py

Now some errors are not supressed in test mode

Strict exceptions processing in tests

---

fedot/api/api_utils/api_composer.py
fedot/api/api_utils/assumptions/assumptions_handler.py
fedot/api/api_utils/presets.py
fedot/api/time.py
test/unit/api/test_presets.py

PR devoted to problem with timeout when automl with more n_jobs  wouldn't applied due to restriction tied with initial assumption fit time

Note n_jobs when choosing preset or deciding doing composing or not 

---

fedot/api/main.py
fedot/core/composer/metrics.py
fedot/core/data/data.py
fedot/core/data/multi_modal.py
fedot/core/pipelines/ts_wrappers.py
test/unit/api/test_main_api.py
test/unit/data/test_data_merge.py
test/unit/data/test_data_merge_text.py
test/unit/data/test_data_merge_ts.py

```Fedot.forecast``` method refactored
#858

Refactor forecast method

---

fedot/api/api_utils/api_composer.py
fedot/api/api_utils/params.py
fedot/api/main.py
fedot/core/caching/base_cache_db.py
fedot/core/caching/pipelines_cache.py
fedot/core/caching/pipelines_cache_db.py
fedot/core/caching/preprocessing_cache.py
fedot/core/caching/preprocessing_cache_db.py
requirements.txt
test/integration/cache/test_parallel_cache_files.py
test/unit/api/test_api_utils.py
test/unit/api/test_main_api.py

The idea is to delete cache files, that are currently not used by the running processes.
`psutil` lib was added to the requirements.txt in order to look at the running processes ids.
Special integration test was created and it can be found at [here](https://github.com/nccr-itmo/FEDOT/blob/824_no_such_table/test/integration/cache/test_parallel_cache_files.py).

improved unused temp files deletion

---

examples/advanced/fedot_based_solutions/external_optimizer.py
examples/advanced/fedot_based_solutions/graph_model_optimization.py
fedot/api/api_utils/api_composer.py
fedot/core/composer/advisor.py
fedot/core/composer/composer_builder.py
fedot/core/optimisers/gp_comp/gp_operators.py
fedot/core/optimisers/gp_comp/gp_optimizer.py
fedot/core/optimisers/gp_comp/operators/mutation.py
fedot/core/optimisers/opt_node_factory.py
fedot/core/optimisers/optimizer.py
fedot/core/optimisers/populational_optimizer.py
fedot/core/pipelines/pipeline_node_factory.py
fedot/core/repository/graph_model_reposiroty.py
fedot/core/repository/graph_operation_reposiroty.py
fedot/core/repository/operation_types_repository.py
fedot/core/repository/pipeline_model_repository.py
fedot/core/repository/pipeline_operation_repository.py
test/unit/api/test_api_utils.py
test/unit/models/test_repository.py
test/unit/optimizer/test_default_node_factory.py
test/unit/optimizer/test_external.py
test/unit/pipelines/test_pipeline_node_factory.py
test/unit/tasks/test_custom.py

Implement Model Repository subsystem for generic graph optimiser

---

.readthedocs.yml
docs/source/advanced/pipeline_import_export.rst
docs/source/conf.py
docs/source/contribution.rst
fedot/api/main.py
fedot/core/operations/data_operation.py
other_requirements/extra.txt
requirements.txt

This change allows checking if warnings were during building documentation

failing doctest dependence on warnings

---

fedot/api/api_utils/api_composer.py
fedot/api/main.py
fedot/core/optimisers/populational_optimizer.py
fedot/core/pipelines/pipeline.py
test/unit/models/test_atomized_model.py
test/unit/validation/test_table_cv.py

Corrects time_constraint for pipeline.fit

Timeout for pipeline fit fix

---

fedot/core/data/multi_modal.py

- added property `class_labels` to MultiModalData class, so now `plot_predictions` works on multimodal data too

Hotfix of multimodal plot visualisation

---

README.rst

Fixes to resolve PyPI publishing error

Readme inlcude fix

---

fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
fedot/core/repository/data/default_operation_params.json

Small fix to avoid FutureWarning
#948

Add default parameter for FastICA

---

fedot/core/pipelines/verification_rules.py

fix for https://github.com/nccr-itmo/FEDOT/issues/944

Fix ignoring some wrong links

---

fedot/api/api_utils/api_data.py
fedot/api/api_utils/api_data_analyser.py
fedot/api/api_utils/predefined_model.py
fedot/core/dag/graph_verifier.py
fedot/core/data/data.py
fedot/core/pipelines/verification.py
fedot/core/pipelines/verification_rules.py
test/unit/adapter/test_adapt_verification_rules.py
test/unit/api/test_api_utils.py
test/unit/api/test_main_api.py
test/unit/pipelines/test_pipeline_verification.py

Fix unused verification rule for consistency of task_type & root node operation

---

fedot/core/adapter/adapter.py
fedot/core/composer/composer_builder.py
fedot/core/dag/graph_delegate.py
fedot/core/optimisers/objective/__init__.py
fedot/core/optimisers/opt_history_objects/individual.py
fedot/core/optimisers/opt_history_objects/opt_history.py
fedot/core/pipelines/template.py
fedot/core/pipelines/tuning/tuner_builder.py
fedot/core/serializers/serializer.py
fedot/core/visualisation/opt_viz_extra.py
test/unit/composer/test_composer.py
test/unit/composer/test_history.py
test/unit/data/test_data_split.py
test/unit/optimizer/test_data_objective_eval.py
test/unit/pipelines/tuning/test_tuner_builder.py
test/unit/serialization/mocks/history_mocks.py
test/unit/visualization/test_composing_history.py

#866 issue + PipelineAdapter was removed since property `historical_pipelines` was the only place it was used in

866 abstract opthistory to be usable for generic graphs

---

examples/advanced/fedot_based_solutions/graph_model_optimization.py
fedot/api/api_utils/api_composer.py
fedot/core/composer/composer_builder.py
fedot/core/optimisers/archive/generation_keeper.py
fedot/core/optimisers/objective/data_objective_eval.py
fedot/core/optimisers/objective/metrics_objective.py
fedot/core/optimisers/objective/objective.py
fedot/core/optimisers/opt_history_objects/opt_history.py
fedot/core/pipelines/tuning/tuner_builder.py
fedot/core/repository/quality_metrics_repository.py
fedot/core/serializers/coders/__init__.py
fedot/core/serializers/coders/objective_serialization.py
fedot/core/serializers/coders/opt_history_serialization.py
fedot/core/serializers/serializer.py
fedot/sensitivity/deletion_methods/multi_times_analysis.py
fedot/sensitivity/node_sa_approaches.py
fedot/utilities/define_metric_by_task.py
test/unit/composer/test_composer.py
test/unit/composer/test_history.py
test/unit/optimizer/gp_operators/test_gp_operators.py
test/unit/optimizer/test_data_objective_eval.py
test/unit/optimizer/test_evaluation.py
test/unit/optimizer/test_generation_keeper.py
test/unit/pipelines/tuning/test_tuner_builder.py
test/unit/tasks/test_custom.py
test/unit/validation/test_table_cv.py

- Abstract Objective from MetricsEnum for GOLEM (it doesn't yet need these Metrics, as they are specific for FEDOT)
- Modify GenerationKeeper to allow improvement watching & adaptive scheme for custom quality & complexity metrics (Resolves #959)

Make Objective more general & fix adaptive pop size scheme

---

docs/source/examples/index.rst
docs/source/examples/notebooks.rst

Resolve: #885
Documentation in [Examples and notebooks](https://fedot.readthedocs.io/en/latest/examples/index.html) section.
The actual page: https://fedot--968.org.readthedocs.build/en/968/examples/index.html

Documentation for `Examples and notebooks`

---

fedot/api/api_utils/api_composer.py
fedot/core/optimisers/gp_comp/gp_optimizer.py
fedot/core/optimisers/opt_history_objects/generation.py
fedot/core/optimisers/opt_history_objects/opt_history.py
fedot/core/optimisers/populational_optimizer.py
fedot/core/serializers/coders/opt_history_serialization.py
fedot/core/serializers/serializer.py
test/unit/composer/test_composer.py
test/unit/composer/test_history.py

This PR is addressed to solve the following issue #846 
Also makes a step towards #866 labeled generations.
Change list:
- Implement class `Genetaion` with ability for generations labeling & other metadata.
- Add `initial_assumptions`, `final_choices` and `tuning_result` to `OptHistory`.
- Implement usage of the new class during evolutionary process.
- Adapt older histories to the changes.

Implement custom class for generations

---

docs/source/advanced/data_preprocessing.rst
fedot/preprocessing/data_types.py
test/unit/preprocessing/test_pipeline_preprocessing.py
test/unit/preprocessing/test_preprocessors.py

Remove categorical_max_classes_th param

---

fedot/core/dag/graph.py
fedot/core/dag/graph_node.py
fedot/core/dag/linked_graph_node.py
fedot/core/pipelines/node.py
fedot/core/pipelines/pipeline.py
fedot/core/pipelines/pipeline_builder.py
fedot/core/pipelines/verification_rules.py
test/unit/pipelines/test_decompose_pipelines.py
test/unit/pipelines/test_pipeline.py
test/unit/serialization/mocks/history_mocks.py

Allow getting nodes by attributes

---

examples/simple/classification/classification_with_tuning.py
examples/simple/time_series_forecasting/api_forecasting.py
fedot/core/operations/evaluation/operation_implementations/implementation_interfaces.py
fedot/core/operations/evaluation/operation_implementations/models/custom_model.py
fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
fedot/core/optimisers/gp_comp/operators/crossover.py
fedot/core/optimisers/gp_comp/operators/mutation.py
fedot/core/pipelines/node.py
fedot/core/pipelines/pipeline.py
fedot/core/pipelines/pipeline_advisor.py
fedot/core/pipelines/pipeline_node_factory.py
fedot/core/pipelines/tuning/search_space.py
fedot/core/pipelines/verification_rules.py
fedot/core/repository/data/default_operation_params.json
fedot/core/validation/split.py
fedot/utilities/debug.py
test/integration/api_params/test_main_api_params.py
test/integration/quality/test_synthetic_tasks.py
test/integration/real_applications/test_examples.py
test/unit/data/test_data_split.py
test/unit/models/test_custom_model_introduction.py
test/unit/optimizer/test_data_objective_eval.py

Solve for issue https://github.com/aimclub/FEDOT/issues/970
PS problem with ts connection will be solved in other PR

Add strict to tests

---

fedot/core/operations/evaluation/operation_implementations/data_operations/categorical_encoders.py
fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_selectors.py
fedot/preprocessing/categorical.py
test/unit/explainability/test_pipeline_explanation.py
test/unit/tasks/test_multi_task.py

Changes: 
- Removed deprecated dataset "Boston"
- Simplified bad-written fixtures
- Added scikit-learn 1.2 compatibility

Hotfix for scikit-learn 1.2

---

.github/README.rst
README.rst
README_en.rst
setup.py

Russian version: https://gitlab.actcognitive.org/itmo-nss-team/FEDOT/-/tree/update_readme

Update readme file and setup

---

fedot/api/api_utils/api_composer.py
fedot/api/api_utils/params.py
fedot/api/main.py
fedot/core/pipelines/tuning/tuner_builder.py
test/unit/api/test_main_api.py
test/unit/pipelines/tuning/test_tuner_builder.py
test/unit/tasks/test_classification.py

Added tune method to API

---

fedot/api/api_utils/api_composer.py
fedot/api/main.py
fedot/core/pipelines/tuning/tuner_interface.py
fedot/core/pipelines/tuning/unified.py
test/unit/api/test_main_api.py

1) Test made more unit-like
2) Fixes in tuner and API

Fix for tuner test

---

README.rst
README_en.rst

Fixed link to codecov in both readme files

Codecov readme hotfix

---

cases/credit_scoring/credit_scoring_problem.py
docs/source/conf.py
examples/advanced/automl/tpot_vs_fedot.py
examples/advanced/multimodal_text_num_example.py
examples/advanced/multiobj_optimisation.py
examples/simple/classification/api_classification.py
examples/simple/interpretable/api_explain.py
examples/simple/regression/api_regression.py
examples/simple/time_series_forecasting/api_forecasting.py
setup.py
test/integration/cache/test_parallel_cache_files.py
test/integration/quality/test_quality_improvement.py
test/integration/quality/test_synthetic_tasks.py
test/integration/real_applications/test_examples.py
test/integration/test_profiler.py

With few integration test fixes for speed (runtime is still too big for GitHub Actions, see #1042).
I have run integration tests locally, it's ok.
Closes #1030

Release 0.6.2

---

.github/workflows/manual-build.yml
.github/workflows/publish_pypi.yml
.travis.yml
README.rst
README_en.rst
docs/source/conf.py
other_requirements/extra.txt
requirements.txt
setup.py

Resolves #1046 , removes 3.7 from requirements.
Supersedes #1053 , also adds 3.10

Release 070 update

---

examples/simple/time_series_forecasting/api_forecasting.py
fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
fedot/core/operations/evaluation/operation_implementations/models/custom_model.py
fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/naive.py
fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
fedot/core/pipelines/node.py
fedot/core/pipelines/pipeline.py
fedot/core/pipelines/pipeline_advisor.py
fedot/core/pipelines/verification_rules.py
fedot/core/repository/data/data_operation_repository.json
fedot/utilities/debug.py
test/unit/models/test_model.py

Fix for https://github.com/aimclub/FEDOT/issues/979

Fix ts wrong links

---

examples/simple/pipeline_import_export.py

Little hotfix of pipeline import export example

Hotfix of pipeline import export example

---

.github/workflows/mirror_repo_to_gitlab.yml
README.rst
README_en.rst
docs/source/faq/features.rst
docs/source/faq/index.rst

- The questions from paper review added to FAQ.
- ITMO badges added to README

Docs updated, badges added

---

fedot/api/api_utils/input_analyser.py
fedot/core/pipelines/pipeline.py

[comment](https://github.com/aimclub/FEDOT/pull/1057#discussion_r1140055365)

minor meta fix

---

fedot/core/composer/metrics.py

- F1 binary averaging chaned to 'binary' istead 'micro'
- Class varaibles for averaging type added (to allow re-assign it)

F1 averaging fix

---

test/unit/pipelines/test_pipeline_comparison.py

A little hotfix to make all unit-tests passing be available.

Remove outdated test handled in thegolem

---

docs/source/faq/features.rst
docs/source/faq/index.rst
docs/source/faq/problem_solving.rst

Redunant section and duplicated title are fixed

Minor fixes of documentation

---

fedot/core/pipelines/pipeline.py

Connected with [this](https://github.com/aimclub/GOLEM/pull/181) PR from GOLEM

Title for Pipeline plots

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Added:
- Code of conduct, 
- Contributing, 
- Issue templates, 
- Pull request template
Resolves: https://github.com/aimclub/FEDOT/issues/1191
Examples: 
- **Pull request template** ![image](https://github.com/aimclub/FEDOT/assets/61294398/83bf0cc9-a3a1-4dae-a675-59a9025b6eae)
- **Issues template** ![image](https://github.com/aimclub/FEDOT/assets/61294398/1f80e7e6-c012-41ec-9cfa-b66fc0d20a64)

Improve community standards

---

README.rst
README_en.rst

This is a 🙋 feature or enhancement.
Fix broken status of "integration badge" in README.
Fix to prevent further problems with image link for "build badge" as well.
Main repository page:

Fix readme tests badges

---

README.rst
README_en.rst

Edit gitlab link in readme files

---

docs/source/advanced/cli_call.rst
docs/source/advanced/gpu_evaluation.rst
docs/source/advanced/hyperparameters_tuning.rst
docs/source/basics/tabular_data.rst
docs/source/basics/ts_forecasting.rst
docs/source/contribution.rst
docs/source/faq/api_usage.rst
docs/source/faq/features.rst
docs/source/index.rst
docs/source/introduction/tutorial/environment_setup/github_installation.rst
fedot/preprocessing/preprocessing.py
test/integration/api/test_main_api.py

Minor fix for documentation

---

.github/workflows/mirror_repo_to_gitlab.yml

Fix gitlab mirroring

---

.github/workflows/mirror_repo_to_gitlab.yml
.github/workflows/unit-build.yml
other_requirements/extra.txt
requirements.txt

Fixes to publish release 0.7.3.2 on PyPi
Failed publish package to PyPi run - https://github.com/aimclub/FEDOT/actions/runs/8849483743

Fixes to publish release 0.7.3.2 on PyPi

---

fedot/core/operations/evaluation/operation_implementations/models/boostings_implementations.py
fedot/preprocessing/preprocessing.py

~~There was no target encoding for test data if it requires.~~
There were bugs in data preparing for boosting models if test data has target not `None`.

hotfix: Bug with target encoding

---

requirements.txt

Sktime fix

---

docker/jupiter/Dockerfile_Jupiter

Fixes Dockerfile with Jupyter Fedot. New requirements are being installed.
https://t.me/FEDOT_helpdesk/1922

Fix Jupyter Dockerfile

---

docs/source/advanced/gpu_evaluation.rst

Commit 4ea3547d102747859b42c0bf5114fbac5c83ccdb changed the location of the GPU Dockerfile. This PR adjusts sources to changes.

Update GPU Dockerfile reference

---

fedot/api/api_utils/api_params_repository.py
fedot/api/api_utils/params.py
fedot/api/main.py
fedot/core/pipelines/tuning/tuner_builder.py
requirements.txt
test/integration/api/test_main_api.py
test/integration/pipelines/tuning/test_pipeline_tuning.py
test/integration/real_applications/test_examples.py
test/integration/real_applications/test_model_result_reproducing.py
test/unit/api/test_api_params.py
test/unit/data_operations/test_time_series_operations.py
test/unit/optimizer/gp_operators/test_mutation.py
test/unit/pipelines/test_reproducibility.py

Доделываю #1278
- Синхронизировал ветку `repr-fix` с `master`, все коммиты объединены в один
- Добавил в requirements.txt GOLEM с изменениями для воспроизводимости.

Reproducibility fixes

---

fedot/core/operations/evaluation/evaluation_interfaces.py

This is a 🔨 code refactoring. 
Added check for NoneType in  #`is_multi_output_task`

Check nontype in multi target

---

requirements.txt

fix: unpin dask and dask-ml, upper limit for sklearn
